-- ACCREDITATION V3: safe, repeatable installation
-- Preserves existing V3 data; re-running resets no progress and deletes no evidence.
create extension if not exists pgcrypto;

create table if not exists public.accreditation_v3_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  job_title text,
  role text not null check (role in ('department_head','quality_office','director')),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.accreditation_v3_projects (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  name_ru text not null,
  name_uz text not null,
  name_en text not null,
  kind text not null check (kind in ('complex','special')),
  created_at timestamptz not null default now()
);

create table if not exists public.accreditation_v3_indicators (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.accreditation_v3_projects(id) on delete cascade,
  code text not null,
  responsible_label text,
  responsible_user_id uuid references auth.users(id) on delete set null,
  status text not null default 'draft' check (status in ('draft','in_progress','review','revision','approved')),
  completion_percent integer not null default 0 check (completion_percent between 0 and 100),
  submitted_at timestamptz,
  approved_at timestamptz,
  updated_at timestamptz not null default now(),
  unique(project_id,code)
);

create table if not exists public.accreditation_v3_documents (
  id uuid primary key default gen_random_uuid(),
  indicator_id uuid not null references public.accreditation_v3_indicators(id) on delete cascade,
  uploaded_by uuid not null references auth.users(id),
  file_name text not null,
  storage_path text not null,
  version integer not null default 1,
  status text not null default 'in_progress',
  created_at timestamptz not null default now()
);

create table if not exists public.accreditation_v3_reviews (
  id uuid primary key default gen_random_uuid(),
  indicator_id uuid not null references public.accreditation_v3_indicators(id) on delete cascade,
  reviewer_id uuid not null references auth.users(id),
  decision text not null check (decision in ('approved','revision')),
  comment text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.accreditation_v3_history (
  id bigint generated always as identity primary key,
  indicator_id uuid not null references public.accreditation_v3_indicators(id) on delete cascade,
  actor_id uuid references auth.users(id),
  old_status text,
  new_status text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

insert into public.accreditation_v3_projects(code,name_ru,name_uz,name_en,kind) values
('complex','Комплексная государственная аккредитация','Kompleks davlat akkreditatsiyasi','Comprehensive state accreditation','complex'),
('special-software-engineering','Специальная аккредитация — Программная инженерия','Maxsus akkreditatsiya — Dasturiy ta’minot muhandisligi','Special accreditation — Software Engineering','special'),
('special-biomedical-instrumentation','Специальная аккредитация — Приборостроение (биомедицинская инженерия)','Maxsus akkreditatsiya — Asboblar muhandisligi (biomedical muhandislik)','Special accreditation — Instrumentation Engineering (Biomedical Engineering)','special')
on conflict(code) do update set name_ru=excluded.name_ru,name_uz=excluded.name_uz,name_en=excluded.name_en,kind=excluded.kind;

insert into public.accreditation_v3_indicators(project_id,code,responsible_label)
values
((select id from public.accreditation_v3_projects where code='complex'),'1.1','Юрисконсульт Юрисконсульт'),
((select id from public.accreditation_v3_projects where code='complex'),'1.2','Юрисконсульт'),
((select id from public.accreditation_v3_projects where code='complex'),'1.3','Секретарь Совета'),
((select id from public.accreditation_v3_projects where code='complex'),'1.4','Секретарь Совета, Заместитель директора по учебной работе'),
((select id from public.accreditation_v3_projects where code='complex'),'1.5','Секретарь Совета'),
((select id from public.accreditation_v3_projects where code='complex'),'1.6','Начальник отдела контроля качества образования'),
((select id from public.accreditation_v3_projects where code='complex'),'1.7','Заведующий канцелярией (секретарь Совета)'),
((select id from public.accreditation_v3_projects where code='complex'),'2.1','Заместитель директора по учебной работе, Главный бухгалтер'),
((select id from public.accreditation_v3_projects where code='complex'),'2.2','Главный бухгалтер'),
((select id from public.accreditation_v3_projects where code='complex'),'2.3','Главный бухгалтер'),
((select id from public.accreditation_v3_projects where code='complex'),'2.4','Главный бухгалтер'),
((select id from public.accreditation_v3_projects where code='complex'),'2.5','Главный бухгалтер'),
((select id from public.accreditation_v3_projects where code='complex'),'3.1','Заместитель директора по учебной работе'),
((select id from public.accreditation_v3_projects where code='complex'),'3.2','Заместитель директора по учебной работе'),
((select id from public.accreditation_v3_projects where code='complex'),'3.3','Заместитель директора по учебной работе'),
((select id from public.accreditation_v3_projects where code='complex'),'3.4','Пресс-секретарь'),
((select id from public.accreditation_v3_projects where code='complex'),'3.5','Заместитель директора по учебной работе'),
((select id from public.accreditation_v3_projects where code='complex'),'4.1','Заместитель директора по учебной работе, начальник отдела международного сотрудничества'),
((select id from public.accreditation_v3_projects where code='complex'),'4.2','Заместитель директора по научной работе и инновациям'),
((select id from public.accreditation_v3_projects where code='complex'),'4.3','Первый заместитель директора по вопросам молодежи, духовности и просвещения'),
((select id from public.accreditation_v3_projects where code='complex'),'4.4','Заместитель директора по учебной работе'),
((select id from public.accreditation_v3_projects where code='complex'),'4.5','Первый заместитель директора по вопросам молодежи, духовности и просвещения'),
((select id from public.accreditation_v3_projects where code='complex'),'5.1','Начальник офиса регистратора'),
((select id from public.accreditation_v3_projects where code='complex'),'5.2','Начальник офиса регистратора'),
((select id from public.accreditation_v3_projects where code='complex'),'5.3','Начальник отдела цифровых образовательных технологий'),
((select id from public.accreditation_v3_projects where code='complex'),'5.4','Начальник отдела цифровых образовательных технологий'),
((select id from public.accreditation_v3_projects where code='complex'),'5.5','Начальник офиса регистратора'),
((select id from public.accreditation_v3_projects where code='complex'),'5.6','Заместитель директора по учебной работе, секретарь Совета'),
((select id from public.accreditation_v3_projects where code='complex'),'6.1','Начальник отдела международного сотрудничества'),
((select id from public.accreditation_v3_projects where code='complex'),'6.2','Начальник отдела научных исследований, инноваций и подготовки научно-педагогических кадров'),
((select id from public.accreditation_v3_projects where code='complex'),'6.3','Заместитель директора по учебной работе'),
((select id from public.accreditation_v3_projects where code='complex'),'6.4','Начальник отдела международного сотрудничества, начальник учебно-методического отдела'),
((select id from public.accreditation_v3_projects where code='complex'),'6.5','Начальник отдела международного сотрудничества'),
((select id from public.accreditation_v3_projects where code='complex'),'6.6','Начальник отдела международного сотрудничества'),
((select id from public.accreditation_v3_projects where code='complex'),'7.1','Начальник отдела контроля качества образования'),
((select id from public.accreditation_v3_projects where code='complex'),'7.2','Начальник отдела контроля качества образования'),
((select id from public.accreditation_v3_projects where code='complex'),'7.3','Начальник отдела контроля качества образования'),
((select id from public.accreditation_v3_projects where code='complex'),'7.4','Заместитель директора по учебной работе'),
((select id from public.accreditation_v3_projects where code='complex'),'7.5','Пресс-секретарь'),
((select id from public.accreditation_v3_projects where code='complex'),'8.1','Начальник отдела контроля качества образования'),
((select id from public.accreditation_v3_projects where code='complex'),'8.2','Начальник отдела контроля качества образования'),
((select id from public.accreditation_v3_projects where code='complex'),'8.3','Начальник отдела контроля качества образования'),
((select id from public.accreditation_v3_projects where code='complex'),'8.4','Начальник отдела контроля качества образования'),
((select id from public.accreditation_v3_projects where code='complex'),'8.5','Начальник отдела контроля качества образования'),
((select id from public.accreditation_v3_projects where code='complex'),'8.6','Начальник отдела контроля качества образования'),
((select id from public.accreditation_v3_projects where code='complex'),'9.1','Заместитель директора по учебной работе'),
((select id from public.accreditation_v3_projects where code='complex'),'9.2','Заместитель директора по учебной работе'),
((select id from public.accreditation_v3_projects where code='complex'),'9.3','Начальник офиса регистратора'),
((select id from public.accreditation_v3_projects where code='complex'),'9.4','Начальник офиса регистратора'),
((select id from public.accreditation_v3_projects where code='complex'),'9.5','Заместитель директора по учебной работе'),
((select id from public.accreditation_v3_projects where code='complex'),'9.6','Начальник отдела контроля качества образования'),
((select id from public.accreditation_v3_projects where code='complex'),'10.1','Заместитель директора по учебной работе'),
((select id from public.accreditation_v3_projects where code='complex'),'10.2','Заместитель директора по учебной работе'),
((select id from public.accreditation_v3_projects where code='complex'),'10.3','Заместитель директора по научной работе'),
((select id from public.accreditation_v3_projects where code='complex'),'10.4','Заместитель директора по учебной работе'),
((select id from public.accreditation_v3_projects where code='complex'),'10.5','Начальник учебно-методического отдела'),
((select id from public.accreditation_v3_projects where code='complex'),'10.6','Начальник учебно-методического отдела'),
((select id from public.accreditation_v3_projects where code='complex'),'10.7','Заместитель директора по научной работе'),
((select id from public.accreditation_v3_projects where code='complex'),'10.8','Начальник учебно-методического отдела'),
((select id from public.accreditation_v3_projects where code='complex'),'11.1','Начальник отдела маркетинга и практики студентов'),
((select id from public.accreditation_v3_projects where code='complex'),'11.2','Начальник отдела маркетинга и практики студентов'),
((select id from public.accreditation_v3_projects where code='complex'),'11.3','Начальник отдела маркетинга и практики студентов'),
((select id from public.accreditation_v3_projects where code='complex'),'11.4','Начальник отдела маркетинга и практики студентов'),
((select id from public.accreditation_v3_projects where code='complex'),'11.5','Начальник отдела маркетинга и практики студентов'),
((select id from public.accreditation_v3_projects where code='complex'),'11.6','Начальник отдела маркетинга и практики студентов'),
((select id from public.accreditation_v3_projects where code='complex'),'12.1','Заместитель директора по учебной работе, ответственный секретарь приемной комиссии'),
((select id from public.accreditation_v3_projects where code='complex'),'12.2','Директор информационно-ресурсного центра'),
((select id from public.accreditation_v3_projects where code='complex'),'12.3','Начальник учебно-методического отдела'),
((select id from public.accreditation_v3_projects where code='complex'),'12.4','Начальник финансово-экономического отдела'),
((select id from public.accreditation_v3_projects where code='complex'),'13.1','Ответственный секретарь приемной комиссии'),
((select id from public.accreditation_v3_projects where code='complex'),'13.2','Ответственный секретарь приемной комиссии'),
((select id from public.accreditation_v3_projects where code='complex'),'13.3','Ответственный секретарь приемной комиссии, начальник центра цифровых образовательных технологий'),
((select id from public.accreditation_v3_projects where code='complex'),'13.4','Ответственный секретарь приемной комиссии'),
((select id from public.accreditation_v3_projects where code='complex'),'13.5','Секретарь апелляционной комиссии'),
((select id from public.accreditation_v3_projects where code='complex'),'13.6','Ответственный секретарь приемной комиссии'),
((select id from public.accreditation_v3_projects where code='complex'),'14.1','Начальник офиса регистратора, деканы факультетов'),
((select id from public.accreditation_v3_projects where code='complex'),'14.2','Начальник офиса регистратора, деканы факультетов'),
((select id from public.accreditation_v3_projects where code='complex'),'14.3','Начальник офиса регистратора, деканы факультетов'),
((select id from public.accreditation_v3_projects where code='complex'),'14.4','Начальник офиса регистратора'),
((select id from public.accreditation_v3_projects where code='complex'),'14.5','Начальник офиса регистратора'),
((select id from public.accreditation_v3_projects where code='complex'),'15.1','Начальник отдела международного сотрудничества'),
((select id from public.accreditation_v3_projects where code='complex'),'15.2','Начальник отдела международного сотрудничества, начальник финансово-экономического отдела'),
((select id from public.accreditation_v3_projects where code='complex'),'15.3','Начальник отдела международного сотрудничества'),
((select id from public.accreditation_v3_projects where code='complex'),'15.4','Начальник отдела международного сотрудничества'),
((select id from public.accreditation_v3_projects where code='complex'),'15.5','Начальник отдела международного сотрудничества'),
((select id from public.accreditation_v3_projects where code='complex'),'15.6','Начальник отдела международного сотрудничества'),
((select id from public.accreditation_v3_projects where code='complex'),'16.1','Начальник отдела международного сотрудничества, ответственный секретарь приемной комиссии'),
((select id from public.accreditation_v3_projects where code='complex'),'16.2','Начальник отдела международного сотрудничества'),
((select id from public.accreditation_v3_projects where code='complex'),'16.3','Начальник отдела международного сотрудничества Заместитель директора по учебной работе'),
((select id from public.accreditation_v3_projects where code='complex'),'16.4','Начальник отдела международного сотрудничества'),
((select id from public.accreditation_v3_projects where code='complex'),'16.5','Заместитель директора по научной работе и инновациям, Начальник финансово-экономического отдела'),
((select id from public.accreditation_v3_projects where code='complex'),'16.6','Начальник отдела международного сотрудничества'),
((select id from public.accreditation_v3_projects where code='complex'),'17.1','Начальник учебно-методического отдела'),
((select id from public.accreditation_v3_projects where code='complex'),'17.2','Начальник учебно-методического отдела Деканы факультетов Заведующие кафедрами'),
((select id from public.accreditation_v3_projects where code='complex'),'17.3','Начальник учебно-методического отдела Деканы факультетов'),
((select id from public.accreditation_v3_projects where code='complex'),'17.4','Начальник учебно-методического отдела'),
((select id from public.accreditation_v3_projects where code='complex'),'17.5','Начальник учебно-методического отдела, начальник офиса регистратора'),
((select id from public.accreditation_v3_projects where code='complex'),'17.6','Начальник учебно-методического отдела Начальник офиса регистратора'),
((select id from public.accreditation_v3_projects where code='complex'),'18.1','Заведующие кафедрами'),
((select id from public.accreditation_v3_projects where code='complex'),'18.2','Заведующие кафедрами'),
((select id from public.accreditation_v3_projects where code='complex'),'18.3','Начальник учебно-методического отдела Заведующие кафедрами'),
((select id from public.accreditation_v3_projects where code='complex'),'18.4','Начальник учебно-методического отдела Заведующие кафедрами'),
((select id from public.accreditation_v3_projects where code='complex'),'19.1','Начальник учебно-методического отдела'),
((select id from public.accreditation_v3_projects where code='complex'),'19.2','Начальник учебно-методического отдела Заведующие кафедрами'),
((select id from public.accreditation_v3_projects where code='complex'),'19.3','Заведующие кафедрами'),
((select id from public.accreditation_v3_projects where code='complex'),'19.4','Заведующие кафедрами'),
((select id from public.accreditation_v3_projects where code='complex'),'19.5','Заведующие кафедрами'),
((select id from public.accreditation_v3_projects where code='complex'),'20.1','Начальник учебно-методического отдела'),
((select id from public.accreditation_v3_projects where code='complex'),'20.2','Начальник учебно-методического отдела Заведующие кафедрами'),
((select id from public.accreditation_v3_projects where code='complex'),'20.3','Заведующие кафедрами'),
((select id from public.accreditation_v3_projects where code='complex'),'20.4','Заведующие кафедрами'),
((select id from public.accreditation_v3_projects where code='complex'),'20.5','Начальник учебно-методического отдела Заведующие кафедрами'),
((select id from public.accreditation_v3_projects where code='complex'),'21.1','Начальник учебно-методического отдела'),
((select id from public.accreditation_v3_projects where code='complex'),'21.2','Заведующие кафедрами'),
((select id from public.accreditation_v3_projects where code='complex'),'21.3','Деканы факультетов, заведующие кафедрами'),
((select id from public.accreditation_v3_projects where code='complex'),'21.4','Заведующие кафедрами'),
((select id from public.accreditation_v3_projects where code='complex'),'21.5','Заведующие кафедрами'),
((select id from public.accreditation_v3_projects where code='complex'),'22.1','Начальник отдела кадров'),
((select id from public.accreditation_v3_projects where code='complex'),'22.2','Начальник отдела кадров'),
((select id from public.accreditation_v3_projects where code='complex'),'22.3','Начальник отдела научных исследований, инноваций и подготовки научно-педагогических кадров'),
((select id from public.accreditation_v3_projects where code='complex'),'22.4','Начальник отдела научных исследований, инноваций и подготовки научно-педагогических кадров'),
((select id from public.accreditation_v3_projects where code='complex'),'22.5','Председатель рабочей группы по KPI'),
((select id from public.accreditation_v3_projects where code='complex'),'23.1','Начальник отдела кадров'),
((select id from public.accreditation_v3_projects where code='complex'),'23.2','Заведующие кафедрами'),
((select id from public.accreditation_v3_projects where code='complex'),'23.3','Начальник отдела кадров'),
((select id from public.accreditation_v3_projects where code='complex'),'23.4','Заведующие кафедрами'),
((select id from public.accreditation_v3_projects where code='complex'),'23.5','Начальник учебно-методического отдела Начальник отдела научных исследований, инноваций и подготовки научно-педагогических кадров'),
((select id from public.accreditation_v3_projects where code='complex'),'24.1','Начальник отдела кадров'),
((select id from public.accreditation_v3_projects where code='complex'),'24.2','Начальник отдела кадров'),
((select id from public.accreditation_v3_projects where code='complex'),'24.3','Начальник отдела кадров'),
((select id from public.accreditation_v3_projects where code='complex'),'24.4','Начальник отдела кадров'),
((select id from public.accreditation_v3_projects where code='complex'),'24.5','Начальник отдела кадров Заведующие кафедрами'),
((select id from public.accreditation_v3_projects where code='complex'),'25.1','Начальник учебно-методического отдела Отдел научных исследований, инноваций и подготовки научно-педагогических кадров'),
((select id from public.accreditation_v3_projects where code='complex'),'25.2','Начальник учебно-методического отдела Начальник отдела научных исследований, инноваций и подготовки научно-педагогических кадров'),
((select id from public.accreditation_v3_projects where code='complex'),'25.3','Начальник отдела международного сотрудничества'),
((select id from public.accreditation_v3_projects where code='complex'),'25.4','Начальник учебно-методического отдела Начальник отдела научных исследований, инноваций и подготовки научно-педагогических кадров'),
((select id from public.accreditation_v3_projects where code='complex'),'25.5','Начальник учебно-методического отдела Начальник отдела научных исследований, инноваций и подготовки научно-педагогических кадров'),
((select id from public.accreditation_v3_projects where code='complex'),'25.6','Начальник учебно-методического отдела Начальник отдела научных исследований, инноваций и подготовки научно-педагогических кадров'),
((select id from public.accreditation_v3_projects where code='complex'),'26.1','Начальник отдела международного сотрудничества'),
((select id from public.accreditation_v3_projects where code='complex'),'26.2','Начальник финансово-экономического отдела'),
((select id from public.accreditation_v3_projects where code='complex'),'26.3','Начальник отдела научных исследований, инноваций и подготовки научно-педагогических кадров'),
((select id from public.accreditation_v3_projects where code='complex'),'26.4','Заведующие кафедрами'),
((select id from public.accreditation_v3_projects where code='complex'),'26.5','Начальник отдела научных исследований, инноваций и подготовки научно-педагогических кадров'),
((select id from public.accreditation_v3_projects where code='complex'),'26.6','Начальник отдела научных исследований, инноваций и подготовки научно-педагогических кадров'),
((select id from public.accreditation_v3_projects where code='complex'),'27.1','Председатель рабочей группы по KPI, Начальник отдела кадров'),
((select id from public.accreditation_v3_projects where code='complex'),'27.2','Председатель рабочей группы по KPI, Начальник отдела кадров'),
((select id from public.accreditation_v3_projects where code='complex'),'27.3','Председатель рабочей группы по KPI, Начальник отдела кадров'),
((select id from public.accreditation_v3_projects where code='complex'),'27.4','Председатель рабочей группы по KPI, Начальник отдела кадров'),
((select id from public.accreditation_v3_projects where code='complex'),'27.5','Председатель рабочей группы по KPI, Начальник отдела кадров'),
((select id from public.accreditation_v3_projects where code='complex'),'28.1','Начальник управления делами, Заведующие кафедрами'),
((select id from public.accreditation_v3_projects where code='complex'),'28.2','Заместитель директора по научной работе и инновациям'),
((select id from public.accreditation_v3_projects where code='complex'),'28.3','Начальник отдела научных исследований, инноваций и подготовки научно-педагогических кадров'),
((select id from public.accreditation_v3_projects where code='complex'),'28.4','Начальник отдела международного сотрудничества Начальник отдела научных исследований, инноваций и подготовки научно-педагогических кадров'),
((select id from public.accreditation_v3_projects where code='complex'),'28.5','Начальник отдела научных исследований, инноваций и подготовки научно-педагогических кадров'),
((select id from public.accreditation_v3_projects where code='complex'),'28.6','Начальник отдела научных исследований, инноваций и подготовки научно-педагогических кадров'),
((select id from public.accreditation_v3_projects where code='complex'),'28.7','Начальник отдела научных исследований, инноваций и подготовки научно-педагогических кадров'),
((select id from public.accreditation_v3_projects where code='complex'),'28.8','Начальник отдела научных исследований, инноваций и подготовки научно-педагогических кадров'),
((select id from public.accreditation_v3_projects where code='complex'),'29.1','Начальник отдела научных исследований, инноваций и подготовки научно-педагогических кадров'),
((select id from public.accreditation_v3_projects where code='complex'),'29.2','Начальник отдела научных исследований, инноваций и подготовки научно-педагогических кадров'),
((select id from public.accreditation_v3_projects where code='complex'),'29.3','Начальник отдела научных исследований, инноваций и подготовки научно-педагогических кадров'),
((select id from public.accreditation_v3_projects where code='complex'),'29.4','Начальник отдела научных исследований, инноваций и подготовки научно-педагогических кадров'),
((select id from public.accreditation_v3_projects where code='complex'),'29.5','Начальник отдела научных исследований, инноваций и подготовки научно-педагогических кадров'),
((select id from public.accreditation_v3_projects where code='complex'),'29.6','Начальник отдела научных исследований, инноваций и подготовки научно-педагогических кадров'),
((select id from public.accreditation_v3_projects where code='complex'),'30.1','Начальник отдела научных исследований, инноваций и подготовки научно-педагогических кадров'),
((select id from public.accreditation_v3_projects where code='complex'),'30.2','Начальник отдела научных исследований, инноваций и подготовки научно-педагогических кадров'),
((select id from public.accreditation_v3_projects where code='complex'),'30.3','Начальник отдела научных исследований, инноваций и подготовки научно-педагогических кадров'),
((select id from public.accreditation_v3_projects where code='complex'),'30.4','Начальник отдела научных исследований, инноваций и подготовки научно-педагогических кадров'),
((select id from public.accreditation_v3_projects where code='complex'),'30.5','Начальник отдела научных исследований, инноваций и подготовки научно-педагогических кадров'),
((select id from public.accreditation_v3_projects where code='complex'),'30.6','Пресс-секретарь'),
((select id from public.accreditation_v3_projects where code='complex'),'30.7','Начальник отдела научных исследований, инноваций и подготовки научно-педагогических кадров'),
((select id from public.accreditation_v3_projects where code='complex'),'31.1','Начальник отдела научных исследований, инноваций и подготовки научно-педагогических кадров'),
((select id from public.accreditation_v3_projects where code='complex'),'31.2','Начальник отдела научных исследований, инноваций и подготовки научно-педагогических кадров'),
((select id from public.accreditation_v3_projects where code='complex'),'31.3','Заведующие кафедрами'),
((select id from public.accreditation_v3_projects where code='complex'),'31.4','Заведующие кафедрами'),
((select id from public.accreditation_v3_projects where code='complex'),'31.5','Начальник отдела научных исследований, инноваций и подготовки научно-педагогических кадров'),
((select id from public.accreditation_v3_projects where code='complex'),'32.1','Директор информационно-ресурсного центра'),
((select id from public.accreditation_v3_projects where code='complex'),'32.2','Директор информационно-ресурсного центра'),
((select id from public.accreditation_v3_projects where code='complex'),'32.3','Директор информационно-ресурсного центра'),
((select id from public.accreditation_v3_projects where code='complex'),'32.4','Начальник отдела научных исследований, инноваций и подготовки научно-педагогических кадров'),
((select id from public.accreditation_v3_projects where code='complex'),'32.5','Начальник отдела научных исследований, инноваций и подготовки научно-педагогических кадров'),
((select id from public.accreditation_v3_projects where code='complex'),'32.6','Директор информационно-ресурсного центра'),
((select id from public.accreditation_v3_projects where code='complex'),'33.1','Начальник отдела научных исследований, инноваций и подготовки научно-педагогических кадров'),
((select id from public.accreditation_v3_projects where code='complex'),'33.2','Начальник отдела научных исследований, инноваций и подготовки научно-педагогических кадров'),
((select id from public.accreditation_v3_projects where code='complex'),'33.3','Начальник отдела научных исследований, инноваций и подготовки научно-педагогических кадров'),
((select id from public.accreditation_v3_projects where code='complex'),'33.4','Начальник отдела научных исследований, инноваций и подготовки научно-педагогических кадров'),
((select id from public.accreditation_v3_projects where code='complex'),'33.5','Начальник отдела научных исследований, инноваций и подготовки научно-педагогических кадров'),
((select id from public.accreditation_v3_projects where code='complex'),'33.6','Начальник отдела научных исследований, инноваций и подготовки научно-педагогических кадров'),
((select id from public.accreditation_v3_projects where code='complex'),'34.1','Начальник отдела научных исследований, инноваций и подготовки научно-педагогических кадров'),
((select id from public.accreditation_v3_projects where code='complex'),'34.2','Начальник отдела научных исследований, инноваций и подготовки научно-педагогических кадров'),
((select id from public.accreditation_v3_projects where code='complex'),'34.3','Начальник отдела научных исследований, инноваций и подготовки научно-педагогических кадров'),
((select id from public.accreditation_v3_projects where code='complex'),'34.4','Начальник отдела научных исследований, инноваций и подготовки научно-педагогических кадров'),
((select id from public.accreditation_v3_projects where code='complex'),'34.5','Начальник отдела научных исследований, инноваций и подготовки научно-педагогических кадров'),
((select id from public.accreditation_v3_projects where code='complex'),'34.6','Начальник отдела научных исследований, инноваций и подготовки научно-педагогических кадров'),
((select id from public.accreditation_v3_projects where code='complex'),'35.1','Начальник отдела научных исследований, инноваций и подготовки научно-педагогических кадров'),
((select id from public.accreditation_v3_projects where code='complex'),'35.2','Начальник отдела научных исследований, инноваций и подготовки научно-педагогических кадров'),
((select id from public.accreditation_v3_projects where code='complex'),'35.3','Начальник отдела научных исследований, инноваций и подготовки научно-педагогических кадров'),
((select id from public.accreditation_v3_projects where code='complex'),'35.4','Главный бухгалтер'),
((select id from public.accreditation_v3_projects where code='complex'),'35.5','Начальник отдела научных исследований, инноваций и подготовки научно-педагогических кадров'),
((select id from public.accreditation_v3_projects where code='complex'),'36.1','Начальник отдела контроля качества образования'),
((select id from public.accreditation_v3_projects where code='complex'),'36.2','Начальник отдела контроля качества образования'),
((select id from public.accreditation_v3_projects where code='complex'),'36.3','Начальник отдела контроля качества образования'),
((select id from public.accreditation_v3_projects where code='complex'),'36.4','Начальник отдела контроля качества образования'),
((select id from public.accreditation_v3_projects where code='complex'),'36.5','Заместитель директора по учебной работе Начальник отдела контроля качества образования'),
((select id from public.accreditation_v3_projects where code='complex'),'36.6','Пресс-секретарь'),
((select id from public.accreditation_v3_projects where code='complex'),'37.1','Первый заместитель директора по вопросам молодежи, духовности и просвещения, Психолог'),
((select id from public.accreditation_v3_projects where code='complex'),'37.2','Первый заместитель директора по вопросам молодежи, духовности и просвещения, Психолог'),
((select id from public.accreditation_v3_projects where code='complex'),'37.3','Начальник отдела маркетинга и практики студентов'),
((select id from public.accreditation_v3_projects where code='complex'),'37.4','Начальник отдела маркетинга и практики студентов'),
((select id from public.accreditation_v3_projects where code='complex'),'37.5','Первый заместитель директора по вопросам молодежи, духовности и просвещения'),
((select id from public.accreditation_v3_projects where code='complex'),'38.1','Первый заместитель директора по вопросам молодежи, духовности и просвещения'),
((select id from public.accreditation_v3_projects where code='complex'),'38.2','Первый заместитель директора по вопросам молодежи, духовности и просвещения'),
((select id from public.accreditation_v3_projects where code='complex'),'38.3','Заместитель директора по научной работе и инновациям'),
((select id from public.accreditation_v3_projects where code='complex'),'38.4','Первый заместитель директора по вопросам молодежи, духовности и просвещения'),
((select id from public.accreditation_v3_projects where code='complex'),'38.5','Первый заместитель директора по вопросам молодежи, духовности и просвещения'),
((select id from public.accreditation_v3_projects where code='complex'),'38.6','Первый заместитель директора по вопросам молодежи, духовности и просвещения'),
((select id from public.accreditation_v3_projects where code='complex'),'39.1','Первый заместитель директора по вопросам молодежи, духовности и просвещения'),
((select id from public.accreditation_v3_projects where code='complex'),'39.2','Первый заместитель директора по вопросам молодежи, духовности и просвещения'),
((select id from public.accreditation_v3_projects where code='complex'),'39.3','Первый заместитель директора по вопросам молодежи, духовности и просвещения'),
((select id from public.accreditation_v3_projects where code='complex'),'39.4','Первый заместитель директора по вопросам молодежи, духовности и просвещения'),
((select id from public.accreditation_v3_projects where code='complex'),'39.5','Первый заместитель директора по вопросам молодежи, духовности и просвещения'),
((select id from public.accreditation_v3_projects where code='complex'),'39.6','Первый заместитель директора по вопросам молодежи, духовности и просвещения, Психолог'),
((select id from public.accreditation_v3_projects where code='complex'),'39.7','Первый заместитель директора по вопросам молодежи, духовности и просвещения'),
((select id from public.accreditation_v3_projects where code='complex'),'40.1','Юрисконсульт'),
((select id from public.accreditation_v3_projects where code='complex'),'40.2','Заведующий сектором по работе с обращениями физических и юридических лиц, контролю и мониторингу'),
((select id from public.accreditation_v3_projects where code='complex'),'40.3','Заместитель заведующего сектором по работе с обращениями физических и юридических лиц, контролю и мониторингу'),
((select id from public.accreditation_v3_projects where code='complex'),'40.4','Заведующий сектором по работе с обращениями физических и юридических лиц, контролю и мониторингу'),
((select id from public.accreditation_v3_projects where code='complex'),'40.5','Заведующий сектором по работе с обращениями физических и юридических лиц, контролю и мониторингу'),
((select id from public.accreditation_v3_projects where code='complex'),'41.1','Начальник управления делами'),
((select id from public.accreditation_v3_projects where code='complex'),'41.2','Начальник управления делами'),
((select id from public.accreditation_v3_projects where code='complex'),'41.3','Начальник управления делами, заведующий кафедрой'),
((select id from public.accreditation_v3_projects where code='complex'),'41.4','Начальник отдела цифровых образовательных технологий'),
((select id from public.accreditation_v3_projects where code='complex'),'41.5','Заместитель директора по учебной работе, Начальник управления делами'),
((select id from public.accreditation_v3_projects where code='complex'),'41.6','Главный бухгалтер'),
((select id from public.accreditation_v3_projects where code='complex'),'41.7','Начальник управления делами'),
((select id from public.accreditation_v3_projects where code='complex'),'42.1','Начальник управления делами'),
((select id from public.accreditation_v3_projects where code='complex'),'42.2','Начальник управления делами, Заведующие кафедрами'),
((select id from public.accreditation_v3_projects where code='complex'),'42.3','Начальник управления делами'),
((select id from public.accreditation_v3_projects where code='complex'),'42.4','Начальник отдела маркетинга и практики студентов'),
((select id from public.accreditation_v3_projects where code='complex'),'42.5','Начальник отдела маркетинга и практики студентов'),
((select id from public.accreditation_v3_projects where code='complex'),'42.6','Начальник отдела маркетинга и практики студентов'),
((select id from public.accreditation_v3_projects where code='complex'),'42.7','Начальник учебно-методического отдела'),
((select id from public.accreditation_v3_projects where code='complex'),'43.1','Директор информационно-ресурсного центра'),
((select id from public.accreditation_v3_projects where code='complex'),'43.2','Директор информационно-ресурсного центра'),
((select id from public.accreditation_v3_projects where code='complex'),'43.3','Директор информационно-ресурсного центра'),
((select id from public.accreditation_v3_projects where code='complex'),'43.4','Директор информационно-ресурсного центра'),
((select id from public.accreditation_v3_projects where code='complex'),'43.5','Директор информационно-ресурсного центра'),
((select id from public.accreditation_v3_projects where code='complex'),'43.6','Директор информационно-ресурсного центра'),
((select id from public.accreditation_v3_projects where code='complex'),'43.7','Директор информационно-ресурсного центра'),
((select id from public.accreditation_v3_projects where code='complex'),'44.1','Начальник управления делами'),
((select id from public.accreditation_v3_projects where code='complex'),'44.2','Директор информационно-ресурсного центра'),
((select id from public.accreditation_v3_projects where code='complex'),'44.3','Начальник отдела цифровых образовательных технологий'),
((select id from public.accreditation_v3_projects where code='complex'),'44.4','Первый заместитель директора по вопросам молодежи, духовности и просвещения'),
((select id from public.accreditation_v3_projects where code='complex'),'44.5','Директор информационно-ресурсного центра'),
((select id from public.accreditation_v3_projects where code='complex'),'45.1','Начальник управления делами'),
((select id from public.accreditation_v3_projects where code='complex'),'45.2','Начальник отдела гражданской защиты и охраны труда'),
((select id from public.accreditation_v3_projects where code='complex'),'45.3','Начальник управления делами'),
((select id from public.accreditation_v3_projects where code='complex'),'45.4','Начальник отдела гражданской защиты и охраны труда'),
((select id from public.accreditation_v3_projects where code='complex'),'45.5','Начальник отдела гражданской защиты и охраны труда'),
((select id from public.accreditation_v3_projects where code='complex'),'46.1','Начальник отдела цифровых образовательных технологий'),
((select id from public.accreditation_v3_projects where code='complex'),'46.2','Начальник отдела цифровых образовательных технологий'),
((select id from public.accreditation_v3_projects where code='complex'),'46.3','Начальник отдела цифровых образовательных технологий'),
((select id from public.accreditation_v3_projects where code='complex'),'46.4','Начальник отдела цифровых образовательных технологий'),
((select id from public.accreditation_v3_projects where code='complex'),'46.5','Начальник отдела цифровых образовательных технологий'),
((select id from public.accreditation_v3_projects where code='complex'),'46.6','Начальник отдела цифровых образовательных технологий'),
((select id from public.accreditation_v3_projects where code='complex'),'47.1','Начальник управления делами'),
((select id from public.accreditation_v3_projects where code='complex'),'47.2','Начальник управления делами'),
((select id from public.accreditation_v3_projects where code='complex'),'47.3','Начальник управления делами'),
((select id from public.accreditation_v3_projects where code='complex'),'47.4','Начальник управления делами'),
((select id from public.accreditation_v3_projects where code='complex'),'47.5','Начальник отдела контроля качества образования'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'1.1.1','Tegishli kafedra mudiri'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'1.1.2','Tegishli kafedra mudiri'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'1.1.3','Tegishli kafedra mudiri'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'1.1.4','Tegishli kafedra mudiri'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'1.1.5','Tegishli kafedra mudiri'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'1.1.6','Tegishli kafedra mudiri'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'1.2.1','Ijrochi direktorning o‘quv ishlari bo‘yicha o‘rinbosari'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'1.2.2','Ijrochi direktorning o‘quv ishlari bo‘yicha o‘rinbosari'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'1.3.1','Ta’lim sifatini nazorat qilish bo‘limi'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'1.3.2','Ta’lim sifatini nazorat qilish bo‘limi'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'1.3.3','Tegishli kafedra mudiri'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'1.3.4','Ta’lim sifatini nazorat qilish bo‘limi'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'1.4.1','Tegishli kafedra mudiri'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'1.4.2','O‘quv-uslubiy bo‘lim'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'1.4.3','Marketing va talabalar amaliyoti bo‘limi'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'1.4.4','Tegishli kafedra mudiri'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'1.5.1','Ta’lim sifatini nazorat qilish bo‘limi'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'1.5.2','Ta’lim sifatini nazorat qilish bo‘limi'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'1.5.3','Ta’lim sifatini nazorat qilish bo‘limi'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'1.5.4','Ta’lim sifatini nazorat qilish bo‘limi'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'1.5.5','Ta’lim sifatini nazorat qilish bo‘limi'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'1.5.6','O‘quv-uslubiy bo‘lim'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'1.5.7','Ta’lim sifatini nazorat qilish bo‘limi'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'2.1.1','Tegishli kafedra mudiri'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'2.1.2','Tegishli kafedra mudiri'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'2.3.1','O‘quv-uslubiy bo‘lim'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'2.4.1','Ta’lim sifatini nazorat qilish bo‘limi'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'2.4.2','Ta’lim sifatini nazorat qilish bo‘limi'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'2.4.3','Tegishli kafedra mudiri'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'2.4.4','Tegishli kafedra mudiri'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'2.4.5','Ta’lim sifatini nazorat qilish bo‘limi'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'2.4.6','O‘quv-uslubiy bo‘lim'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'3.1.1','O‘quv-uslubiy bo‘lim'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'3.2.1','Marketing va talabalar amaliyoti bo‘limi'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'3.2.2','Tegishli kafedra mudiri'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'3.2.3','Marketing va talabalar amaliyoti bo‘limi'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'3.2.4','Tegishli kafedra mudiri'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'3.3.1','O‘quv-uslubiy bo‘lim'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'3.3.2','Ta’lim sifatini nazorat qilish bo‘limi'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'3.3.3','O‘quv-uslubiy bo‘lim'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'3.3.4','O‘quv-uslubiy bo‘lim'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'3.4.1','Tegishli kafedra mudiri'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'3.4.2','Tegishli kafedra mudiri'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'3.4.3','Tegishli kafedra mudiri'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'3.4.4','Ta’lim sifatini nazorat qilish bo‘limi'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'3.4.5','O‘quv-uslubiy bo‘lim'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'3.4.6','O‘quv-uslubiy bo‘lim'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'3.4.7','O‘quv-uslubiy bo‘lim'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'3.5.1','O‘quv-uslubiy bo‘lim'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'3.5.2','O‘quv-uslubiy bo‘lim'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'3.5.3','O‘quv-uslubiy bo‘lim'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'3.5.4','O‘quv-uslubiy bo‘lim'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'3.6.1','Registrator ofisi'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'3.6.2','Apellyatsiya komissiyasi'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'3.6.3','Ta’lim sifatini nazorat qilish bo‘limi'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'3.7.1','O‘quv-uslubiy bo‘lim'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'3.7.2','O‘quv-uslubiy bo‘lim'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'3.7.3','Komplayens-nazorat bo‘limi'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'3.7.4','Komplayens-nazorat bo‘limi'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'3.7.5','Komplayens-nazorat bo‘limi'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'3.7.6','Ijrochi direktorning ilmiy ishlar bo‘yicha o‘rinbosari'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'4.1.1','Qabul komissiyasi'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'4.1.2','Qabul komissiyasi'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'4.2.1','Qabul komissiyasi'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'4.3.1','Registrator ofisi'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'4.3.2','Registrator ofisi'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'4.4.1','Ijrochi direktorning yoshlar bilan ishlash bo‘yicha o‘rinbosari'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'4.4.2','Ijrochi direktorning yoshlar bilan ishlash bo‘yicha o‘rinbosari'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'4.4.3','Dekanatlar'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'4.4.4','O‘quv-uslubiy bo‘lim'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'4.4.5','Ta’lim sifatini nazorat qilish bo‘limi'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'5.1.1','Xodimlar bo‘limi'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'5.2.1','Tegishli kafedra mudiri'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'5.2.2','Tegishli kafedra mudiri'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'5.2.3','Xodimlar bo‘limi'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'5.2.4','Ijrochi direktorning ilmiy ishlar bo‘yicha o‘rinbosari'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'5.2.5','Xodimlar bo‘limi'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'5.4.1','Xalqaro hamkorlik bo‘limi'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'6.1.1','Ishlar boshqarmasi boshlig‘i'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'6.1.2','Tegishli kafedra mudiri'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'6.1.3','Tegishli kafedra mudiri'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'6.1.4','Ishlar boshqarmasi boshlig‘i'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'6.2.1','Axborot-resurs markazi (kutubxona)'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'6.2.2','Axborot-resurs markazi (kutubxona)'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'6.2.3','Tegishli kafedra mudiri'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'6.3.1','Ishlar boshqarmasi boshlig‘i'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'6.4.1','Ijrochi direktorning yoshlar bilan ishlash bo‘yicha o‘rinbosari'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'6.4.2','Xodimlar bo‘limi'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'6.4.3','Ta’lim sifatini nazorat qilish bo‘limi'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'6.5.1','Axborot-resurs markazi (kutubxona)'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'6.5.2','Axborot-resurs markazi (kutubxona)'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'6.6.1','O‘quv-uslubiy bo‘lim'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'6.6.2','Registrator ofisi'),
((select id from public.accreditation_v3_projects where code='special-software-engineering'),'6.6.3','Raqamli va axborot texnologiyalari bo‘limi'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'1.1.1','Tegishli kafedra mudiri'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'1.1.2','Tegishli kafedra mudiri'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'1.1.3','Tegishli kafedra mudiri'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'1.1.4','Tegishli kafedra mudiri'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'1.1.5','Tegishli kafedra mudiri'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'1.1.6','Tegishli kafedra mudiri'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'1.2.1','Ijrochi direktorning o‘quv ishlari bo‘yicha o‘rinbosari'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'1.2.2','Ijrochi direktorning o‘quv ishlari bo‘yicha o‘rinbosari'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'1.3.1','Ta’lim sifatini nazorat qilish bo‘limi'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'1.3.2','Ta’lim sifatini nazorat qilish bo‘limi'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'1.3.3','Tegishli kafedra mudiri'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'1.3.4','Ta’lim sifatini nazorat qilish bo‘limi'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'1.4.1','Tegishli kafedra mudiri'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'1.4.2','O‘quv-uslubiy bo‘lim'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'1.4.3','Marketing va talabalar amaliyoti bo‘limi'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'1.4.4','Tegishli kafedra mudiri'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'1.5.1','Ta’lim sifatini nazorat qilish bo‘limi'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'1.5.2','Ta’lim sifatini nazorat qilish bo‘limi'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'1.5.3','Ta’lim sifatini nazorat qilish bo‘limi'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'1.5.4','Ta’lim sifatini nazorat qilish bo‘limi'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'1.5.5','Ta’lim sifatini nazorat qilish bo‘limi'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'1.5.6','O‘quv-uslubiy bo‘lim'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'1.5.7','Ta’lim sifatini nazorat qilish bo‘limi'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'2.1.1','Tegishli kafedra mudiri'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'2.1.2','Tegishli kafedra mudiri'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'2.3.1','O‘quv-uslubiy bo‘lim'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'2.4.1','Ta’lim sifatini nazorat qilish bo‘limi'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'2.4.2','Ta’lim sifatini nazorat qilish bo‘limi'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'2.4.3','Tegishli kafedra mudiri'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'2.4.4','Tegishli kafedra mudiri'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'2.4.5','Ta’lim sifatini nazorat qilish bo‘limi'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'2.4.6','O‘quv-uslubiy bo‘lim'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'3.1.1','O‘quv-uslubiy bo‘lim'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'3.2.1','Marketing va talabalar amaliyoti bo‘limi'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'3.2.2','Tegishli kafedra mudiri'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'3.2.3','Marketing va talabalar amaliyoti bo‘limi'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'3.2.4','Tegishli kafedra mudiri'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'3.3.1','O‘quv-uslubiy bo‘lim'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'3.3.2','Ta’lim sifatini nazorat qilish bo‘limi'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'3.3.3','O‘quv-uslubiy bo‘lim'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'3.3.4','O‘quv-uslubiy bo‘lim'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'3.4.1','Tegishli kafedra mudiri'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'3.4.2','Tegishli kafedra mudiri'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'3.4.3','Tegishli kafedra mudiri'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'3.4.4','Ta’lim sifatini nazorat qilish bo‘limi'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'3.4.5','O‘quv-uslubiy bo‘lim'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'3.4.6','O‘quv-uslubiy bo‘lim'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'3.4.7','O‘quv-uslubiy bo‘lim'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'3.5.1','O‘quv-uslubiy bo‘lim'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'3.5.2','O‘quv-uslubiy bo‘lim'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'3.5.3','O‘quv-uslubiy bo‘lim'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'3.5.4','O‘quv-uslubiy bo‘lim'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'3.6.1','Registrator ofisi'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'3.6.2','Apellyatsiya komissiyasi'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'3.6.3','Ta’lim sifatini nazorat qilish bo‘limi'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'3.7.1','O‘quv-uslubiy bo‘lim'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'3.7.2','O‘quv-uslubiy bo‘lim'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'3.7.3','Komplayens-nazorat bo‘limi'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'3.7.4','Komplayens-nazorat bo‘limi'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'3.7.5','Komplayens-nazorat bo‘limi'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'3.7.6','Ijrochi direktorning ilmiy ishlar bo‘yicha o‘rinbosari'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'4.1.1','Qabul komissiyasi'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'4.1.2','Qabul komissiyasi'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'4.2.1','Qabul komissiyasi'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'4.3.1','Registrator ofisi'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'4.3.2','Registrator ofisi'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'4.4.1','Ijrochi direktorning yoshlar bilan ishlash bo‘yicha o‘rinbosari'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'4.4.2','Ijrochi direktorning yoshlar bilan ishlash bo‘yicha o‘rinbosari'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'4.4.3','Dekanatlar'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'4.4.4','O‘quv-uslubiy bo‘lim'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'4.4.5','Ta’lim sifatini nazorat qilish bo‘limi'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'5.1.1','Xodimlar bo‘limi'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'5.2.1','Tegishli kafedra mudiri'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'5.2.2','Tegishli kafedra mudiri'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'5.2.3','Xodimlar bo‘limi'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'5.2.4','Ijrochi direktorning ilmiy ishlar bo‘yicha o‘rinbosari'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'5.2.5','Xodimlar bo‘limi'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'5.4.1','Xalqaro hamkorlik bo‘limi'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'6.1.1','Ishlar boshqarmasi boshlig‘i'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'6.1.2','Tegishli kafedra mudiri'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'6.1.3','Tegishli kafedra mudiri'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'6.1.4','Ishlar boshqarmasi boshlig‘i'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'6.2.1','Axborot-resurs markazi (kutubxona)'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'6.2.2','Axborot-resurs markazi (kutubxona)'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'6.2.3','Tegishli kafedra mudiri'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'6.3.1','Ishlar boshqarmasi boshlig‘i'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'6.4.1','Ijrochi direktorning yoshlar bilan ishlash bo‘yicha o‘rinbosari'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'6.4.2','Xodimlar bo‘limi'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'6.4.3','Ta’lim sifatini nazorat qilish bo‘limi'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'6.5.1','Axborot-resurs markazi (kutubxona)'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'6.5.2','Axborot-resurs markazi (kutubxona)'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'6.6.1','O‘quv-uslubiy bo‘lim'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'6.6.2','Registrator ofisi'),
((select id from public.accreditation_v3_projects where code='special-biomedical-instrumentation'),'6.6.3','Raqamli va axborot texnologiyalari bo‘limi')
on conflict(project_id,code) do update set responsible_label=excluded.responsible_label;

create or replace view public.accreditation_v3_project_progress as
select p.code project_code,p.name_ru,p.name_uz,p.name_en,
 count(i.id)::int total,
 count(i.id) filter(where i.status='approved')::int approved,
 count(i.id) filter(where i.status='review')::int review,
 count(i.id) filter(where i.status='revision')::int revision,
 count(i.id) filter(where i.status='in_progress')::int in_progress,
 count(i.id) filter(where i.status='draft')::int draft,
 coalesce(round(avg(i.completion_percent)),0)::int progress
from public.accreditation_v3_projects p
left join public.accreditation_v3_indicators i on i.project_id=p.id
group by p.id,p.code,p.name_ru,p.name_uz,p.name_en;

create or replace function public.accreditation_v3_is_reviewer()
returns boolean language sql stable security definer set search_path=public as $$
 select coalesce((auth.jwt()->'app_metadata'->>'role')='admin',false)
 or exists(select 1 from public.accreditation_v3_profiles p where p.user_id=auth.uid() and p.is_active and p.role='quality_office');
$$;

create or replace function public.accreditation_v3_is_director()
returns boolean language sql stable security definer set search_path=public as $$
 select exists(select 1 from public.accreditation_v3_profiles p where p.user_id=auth.uid() and p.is_active and p.role='director');
$$;

alter table public.accreditation_v3_profiles enable row level security;
alter table public.accreditation_v3_projects enable row level security;
alter table public.accreditation_v3_indicators enable row level security;
alter table public.accreditation_v3_documents enable row level security;
alter table public.accreditation_v3_reviews enable row level security;
alter table public.accreditation_v3_history enable row level security;

do $$
declare r record;
begin
 for r in select policyname,tablename from pg_policies where schemaname='public' and tablename like 'accreditation_v3_%'
 loop execute format('drop policy if exists %I on public.%I',r.policyname,r.tablename); end loop;
end $$;

create policy "v3 public projects" on public.accreditation_v3_projects for select to anon,authenticated using(true);
create policy "v3 public indicator progress" on public.accreditation_v3_indicators for select to anon,authenticated using(true);
create policy "v3 own profile" on public.accreditation_v3_profiles for select to authenticated
 using(user_id=auth.uid() or public.accreditation_v3_is_reviewer() or public.accreditation_v3_is_director());
create policy "v3 department update own indicators" on public.accreditation_v3_indicators for update to authenticated
 using(responsible_user_id=auth.uid() or public.accreditation_v3_is_reviewer())
 with check(responsible_user_id=auth.uid() or public.accreditation_v3_is_reviewer());
create policy "v3 documents read permitted" on public.accreditation_v3_documents for select to authenticated
 using(uploaded_by=auth.uid() or public.accreditation_v3_is_reviewer() or public.accreditation_v3_is_director());
create policy "v3 documents upload own" on public.accreditation_v3_documents for insert to authenticated
 with check(uploaded_by=auth.uid() and exists(select 1 from public.accreditation_v3_indicators i where i.id=indicator_id and i.responsible_user_id=auth.uid()));
create policy "v3 reviews read" on public.accreditation_v3_reviews for select to authenticated
 using(public.accreditation_v3_is_reviewer() or public.accreditation_v3_is_director() or exists(select 1 from public.accreditation_v3_indicators i where i.id=indicator_id and i.responsible_user_id=auth.uid()));
create policy "v3 reviewer creates review" on public.accreditation_v3_reviews for insert to authenticated
 with check(public.accreditation_v3_is_reviewer() and reviewer_id=auth.uid());
create policy "v3 history read" on public.accreditation_v3_history for select to authenticated
 using(public.accreditation_v3_is_reviewer() or public.accreditation_v3_is_director() or exists(select 1 from public.accreditation_v3_indicators i where i.id=indicator_id and i.responsible_user_id=auth.uid()));

grant select on public.accreditation_v3_project_progress to anon,authenticated;

create or replace view public.accreditation_v3_responsible_progress as
select i.responsible_label,
 count(*)::int total,
 count(*) filter(where i.status='approved')::int approved,
 count(*) filter(where i.status='review')::int review,
 count(*) filter(where i.status='revision')::int revision,
 count(*) filter(where i.status='in_progress')::int in_progress,
 count(*) filter(where i.status='draft')::int draft,
 coalesce(round(avg(i.completion_percent)),0)::int progress
from public.accreditation_v3_indicators i
where coalesce(i.responsible_label,'') <> ''
group by i.responsible_label;

grant select on public.accreditation_v3_responsible_progress to authenticated;


insert into storage.buckets(id,name,public,file_size_limit)
values('accreditation-v3-evidence','accreditation-v3-evidence',false,52428800)
on conflict(id) do update set public=false,file_size_limit=excluded.file_size_limit;

drop policy if exists "v3 evidence upload" on storage.objects;
drop policy if exists "v3 evidence read" on storage.objects;
create policy "v3 evidence upload" on storage.objects for insert to authenticated
 with check(bucket_id='accreditation-v3-evidence');
create policy "v3 evidence read" on storage.objects for select to authenticated
 using(bucket_id='accreditation-v3-evidence');

create or replace function public.accreditation_v3_log_status()
returns trigger language plpgsql security definer set search_path=public as $$
begin
 if old.status is distinct from new.status then
   insert into public.accreditation_v3_history(indicator_id,actor_id,old_status,new_status,details)
   values(new.id,auth.uid(),old.status,new.status,jsonb_build_object('completion_percent',new.completion_percent));
 end if;
 new.updated_at=now();
 return new;
end $$;
drop trigger if exists accreditation_v3_status_trigger on public.accreditation_v3_indicators;
create trigger accreditation_v3_status_trigger before update on public.accreditation_v3_indicators
for each row execute function public.accreditation_v3_log_status();

select 'ACCREDITATION V3 INSTALLED' result,
 (select count(*) from public.accreditation_v3_indicators) total_indicators,
 (select count(*) from public.accreditation_v3_projects) projects;
