"use client";
import { useState } from "react";
import { ArrowUpRight, FileText, LayoutList, Users } from "lucide-react";
import { Link } from "@/i18n/routing";
import { accreditationUi } from "@/lib/accreditation/ui";
import { specialPrograms, type Locale } from "@/lib/accreditation/specialData";
import ProjectProgress from "./ProjectProgress";
const copy={ru:{complex:"Комплексная",special:"Специализированная",complexText:"Подготовка института к государственной аккредитации: индикаторы, самооценка и доказательная база.",specialText:"Подготовка образовательных программ: показатели качества, ответственные и доказательства.",count:"индикаторов",deadlines:"Сроки и ответственные",deadlinesText:"Актуальные назначения и сроки доступны в реестре индикаторов. Рабочие материалы открываются после входа с соответствующими правами.",materials:"Материалы и самооценка",loginNote:"Войдите в кабинет для работы с назначенными индикаторами."},uz:{complex:"Kompleks",special:"Maxsus",complexText:"Institutni davlat akkreditatsiyasiga tayyorlash: indikatorlar, o‘zini o‘zi baholash va dalillar bazasi.",specialText:"Ta’lim dasturlarini tayyorlash: sifat ko‘rsatkichlari, mas’ullar va dalillar.",count:"indikator",deadlines:"Muddatlar va mas’ullar",deadlinesText:"Amaldagi vazifalar va muddatlar indikatorlar ro‘yxatida mavjud. Ishchi materiallar tegishli huquqlar bilan tizimga kirgandan so‘ng ochiladi.",materials:"Materiallar va o‘zini o‘zi baholash",loginNote:"Biriktirilgan indikatorlar bilan ishlash uchun kabinetga kiring."},en:{complex:"Institutional",special:"Programme",complexText:"Prepare the institution for state accreditation: indicators, self-assessment and evidence.",specialText:"Prepare educational programmes: quality indicators, owners and evidence.",count:"indicators",deadlines:"Deadlines and owners",deadlinesText:"Current assignments and deadlines are available in the indicator register. Working materials require sign-in and the appropriate permissions.",materials:"Materials and self-assessment",loginNote:"Sign in to work with your assigned indicators."}};
export default function AccreditationOverview({locale,initialType="complex"}:{locale:Locale;initialType?:string}){
 const [type,setType]=useState(initialType==='special'?'special':'complex');const [program,setProgram]=useState<string>(specialPrograms[0].slug);const t=accreditationUi[locale],c=copy[locale];const complex=type==='complex';const href=complex?'/accreditation/complex':`/accreditation/special?program=${program}`;
 return <section className="mt-7"><div role="tablist" aria-label={t.label} className="accreditation-tabs">{(['complex','special'] as const).map(key=><button key={key} id={`accreditation-tab-${key}`} role="tab" aria-selected={type===key} aria-controls={`accreditation-panel-${key}`} tabIndex={type===key?0:-1} onClick={()=>setType(key)} onKeyDown={e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const next=e.key==='Home'?'complex':e.key==='End'?'special':type==='complex'?'special':'complex';setType(next);document.getElementById(`accreditation-tab-${next}`)?.focus()}}} className={type===key?'is-active':''}>{c[key]}</button>)}</div>
 <div role="tabpanel" id={`accreditation-panel-${type}`} aria-labelledby={`accreditation-tab-${type}`} className="mt-5 rounded-2xl border border-slate-200 bg-white p-5 sm:p-7">
  <div className="flex flex-wrap items-start justify-between gap-4"><div className="max-w-3xl"><h2 className="text-2xl font-bold">{complex?t.complex:t.special}</h2><p className="mt-3 text-sm leading-6 text-slate-600">{complex?c.complexText:c.specialText}</p></div><span className="rounded-xl bg-blue-50 px-4 py-3 text-sm font-semibold text-blue-800">{complex?272:94} {c.count}</span></div>
  {!complex&&<div className="mt-5 flex flex-wrap gap-2">{specialPrograms.map(p=><button key={p.slug} onClick={()=>setProgram(p.slug)} aria-pressed={program===p.slug} className={`rounded-lg border px-4 py-3 text-sm ${program===p.slug?'border-teal-600 bg-teal-50 text-teal-900':'border-slate-200'}`}>{p.title[locale]}</button>)}</div>}
  <ProjectProgress projectCodes={[complex?'complex':`special-${program}`]} locale={locale} fallbackTotal={complex?272:94}/>
  <div className="mt-6 grid gap-3 md:grid-cols-3">{([[t.indicators,href,LayoutList],[t.groups,complex?'/accreditation/complex/working-groups':href,Users],[c.materials,complex?'/accreditation/complex/self-assessment':href,FileText]] as const).map(([label,path,Icon])=><Link key={String(label)} href={String(path)} className="accreditation-resource"><Icon size={21}/><span className="flex-1">{String(label)}</span><ArrowUpRight size={17}/></Link>)}</div>
  <div className="mt-6 rounded-xl bg-slate-50 p-4"><h3 className="text-sm font-bold">{c.deadlines}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{c.deadlinesText}</p></div>
  <div className="mt-6 flex flex-wrap items-center gap-4"><Link href={href} className="btn-primary">{t.open}<ArrowUpRight size={18}/></Link><p className="text-sm text-slate-500">{c.loginNote}</p></div>
 </div></section>;
}
