"use client";
import {useState} from "react";
import type {Locale} from "@/lib/accreditation/specialData";

export default function AccreditationResetButton({locale:l}:{locale:Locale}){
 const[busy,setBusy]=useState(false),[msg,setMsg]=useState("");
 const t={ru:{title:"Начать работу с чистой базы",text:"Удалить все текущие файлы, письменные ответы и решения проверки. Назначения сотрудников и индикаторы сохранятся.",button:"Обнулить материалы аккредитации",confirm:"Вы уверены? Все загруженные материалы и принятые ответы будут безвозвратно удалены, а прогресс станет 0%.",done:"Материалы удалены. Все показатели обнулены."},uz:{title:"Toza baza bilan ishni boshlash",text:"Joriy fayllar, yozma javoblar va tekshiruv qarorlarini o‘chirish. Xodim biriktirishlari va indikatorlar saqlanadi.",button:"Akkreditatsiya materiallarini nolga tushirish",confirm:"Ishonchingiz komilmi? Barcha yuklangan materiallar va qabul qilingan javoblar qaytarib bo‘lmaydigan tarzda o‘chiriladi, jarayon 0% bo‘ladi.",done:"Materiallar o‘chirildi. Barcha ko‘rsatkichlar nolga tushirildi."},en:{title:"Start with a clean database",text:"Delete all current files, written responses and review decisions. Employee assignments and indicators remain intact.",button:"Reset accreditation materials",confirm:"Are you sure? All uploaded materials and approved responses will be permanently deleted and progress will return to 0%.",done:"Materials deleted. All progress has been reset."}}[l];
 async function reset(){if(!confirm(t.confirm))return;setBusy(true);setMsg("");const r=await fetch("/api/admin/accreditation/reset",{method:"POST"}),body=await r.json();setBusy(false);setMsg(r.ok?t.done:body.error||"Error");if(r.ok)setTimeout(()=>location.reload(),1200)}
 return <section className="mb-6 rounded-2xl border border-red-200 bg-red-50 p-4 sm:p-5"><h2 className="font-black text-red-900">{t.title}</h2><p className="mt-1 text-sm text-red-800">{t.text}</p><button disabled={busy} onClick={()=>void reset()} className="mt-3 w-full rounded-xl bg-red-700 px-4 py-3 font-bold text-white disabled:opacity-40 sm:w-auto">{busy?"…":t.button}</button>{msg&&<p className="mt-3 text-sm font-bold text-red-800">{msg}</p>}</section>;
}
