"use client";
import {useCallback,useEffect,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase/client";
import type {Locale} from "@/lib/accreditation/specialData";
import {projectLabel} from "@/lib/accreditation/localization";

type Entry={id:number;code:string;project_code:string;actor_name:string|null;action:string;old_status:string|null;new_status:string|null;details:Record<string,unknown>|null;created_at:string};
export default function ActionJournal({locale:l,projectCode}:{locale:Locale;projectCode:string}){
 const s=useMemo(()=>createClient(),[]),[rows,setRows]=useState<Entry[]>([]),[q,setQ]=useState(""),[action,setAction]=useState("all"),[page,setPage]=useState(1),[msg,setMsg]=useState(""),[busy,setBusy]=useState<number|null>(null);
 const t={ru:{title:"Журнал действий",search:"Код, сотрудник или действие",all:"Все действия",empty:"Записей пока нет",remove:"Удалить ошибочную запись",confirm:"Удалить эту запись журнала?",page:"Страница",actions:{document_uploaded:"Файл загружен",document_deleted:"Файл удалён",review_added:"Решение добавлено",status_changed:"Статус изменён"}},uz:{title:"Amallar jurnali",search:"Kod, xodim yoki amal",all:"Barcha amallar",empty:"Hozircha yozuvlar yo‘q",remove:"Noto‘g‘ri yozuvni o‘chirish",confirm:"Jurnal yozuvi o‘chirilsinmi?",page:"Sahifa",actions:{document_uploaded:"Fayl yuklandi",document_deleted:"Fayl o‘chirildi",review_added:"Qaror qo‘shildi",status_changed:"Holat o‘zgardi"}},en:{title:"Action journal",search:"Code, employee or action",all:"All actions",empty:"No entries yet",remove:"Delete incorrect entry",confirm:"Delete this journal entry?",page:"Page",actions:{document_uploaded:"File uploaded",document_deleted:"File deleted",review_added:"Decision added",status_changed:"Status changed"}}}[l];
 const load=useCallback(async()=>{let query=s.from("accreditation_v6_audit_log").select("id,code,project_code,actor_name,action,old_status,new_status,details,created_at").order("created_at",{ascending:false}).limit(300);if(projectCode!=="all")query=query.eq("project_code",projectCode);const{data}=await query;setRows((data||[]) as Entry[])},[s,projectCode]);
 useEffect(()=>{void load()},[load]);
 const label=(value:string)=>t.actions[value as keyof typeof t.actions]||value.replaceAll("_"," "),filtered=rows.filter(x=>(action==="all"||x.action===action)&&(!q||`${x.code} ${x.actor_name||""} ${label(x.action)}`.toLowerCase().includes(q.toLowerCase()))),size=15,pages=Math.max(1,Math.ceil(filtered.length/size)),visible=filtered.slice((page-1)*size,page*size);
 async function remove(id:number){if(!confirm(t.confirm))return;setBusy(id);const r=await fetch(`/api/admin/accreditation/history/${id}`,{method:"DELETE"}),body=await r.json();setBusy(null);setMsg(r.ok?"✓":body.error||"Error");if(r.ok)void load()}
 return <section className="mt-6 rounded-[26px] border bg-white p-4 shadow-sm sm:p-6"><h2 className="text-2xl font-black">{t.title}</h2><div className="mt-4 grid gap-3 md:grid-cols-[1fr_260px]"><input value={q} onChange={e=>{setQ(e.target.value);setPage(1)}} placeholder={t.search} className="min-w-0 rounded-xl border p-3"/><select value={action} onChange={e=>{setAction(e.target.value);setPage(1)}} className="rounded-xl border bg-white p-3"><option value="all">{t.all}</option>{[...new Set(rows.map(x=>x.action))].map(x=><option key={x} value={x}>{label(x)}</option>)}</select></div>{msg&&<p className="mt-3 text-sm text-blue-700">{msg}</p>}<div className="mt-4 overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead><tr className="border-b text-slate-500"><th className="p-3">ID</th><th className="p-3">{l==="ru"?"Индикатор":l==="uz"?"Indikator":"Indicator"}</th><th className="p-3">{l==="ru"?"Действие":l==="uz"?"Amal":"Action"}</th><th className="p-3">{l==="ru"?"Сотрудник":l==="uz"?"Xodim":"Employee"}</th><th className="p-3">{l==="ru"?"Дата":l==="uz"?"Sana":"Date"}</th><th className="p-3"/></tr></thead><tbody>{visible.map(x=><tr key={x.id} className="border-b align-top"><td className="p-3 text-slate-400">{x.id}</td><td className="p-3"><b>{x.code}</b><br/><span className="text-xs text-slate-500">{projectLabel(x.project_code,l)}</span></td><td className="p-3">{label(x.action)}</td><td className="p-3">{x.actor_name||"—"}</td><td className="p-3 whitespace-nowrap">{new Date(x.created_at).toLocaleString(l)}</td><td className="p-3"><button disabled={busy===x.id} onClick={()=>void remove(x.id)} className="rounded-lg bg-red-50 px-3 py-2 font-bold text-red-700 disabled:opacity-40">{t.remove}</button></td></tr>)}</tbody></table>{!visible.length&&<p className="p-6 text-center text-slate-500">{t.empty}</p>}</div><div className="mt-4 flex justify-end gap-2"><button disabled={page<=1} onClick={()=>setPage(x=>x-1)} className="rounded-lg bg-slate-100 px-3 py-2 disabled:opacity-40">←</button><span className="p-2">{t.page} {page}/{pages}</span><button disabled={page>=pages} onClick={()=>setPage(x=>x+1)} className="rounded-lg bg-slate-100 px-3 py-2 disabled:opacity-40">→</button></div></section>
}
