"use client";
import {useCallback,useEffect,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase/client";
import type {Locale} from "@/lib/accreditation/specialData";
import {accreditationPositions as positions,positionLabel} from "@/lib/accreditation/positions";
import {positionKeyLabel,responsibleLabel,projectLabel} from "@/lib/accreditation/localization";
import BulkAssignment from "./BulkAssignment";
import AccreditationControlCenter from "./AccreditationControlCenter";
import IndicatorCollaboration from "./IndicatorCollaboration";
import EmployeeAccountImport from "./EmployeeAccountImport";
import EmployeePositionManager from "./EmployeePositionManager";
type Row=Record<string,any>;
export default function AdminAccreditation({locale:l}:{locale:Locale}){
 const supabase=useMemo(()=>createClient(),[]),[profiles,setProfiles]=useState<Row[]>([]),[items,setItems]=useState<Row[]>([]),[docs,setDocs]=useState<Row[]>([]),[stats,setStats]=useState<Row[]>([]),[owners,setOwners]=useState<Row[]>([]),[msg,setMsg]=useState(""),[comments,setComments]=useState<Record<string,string>>({}),[drafts,setDrafts]=useState<Record<string,string>>({}),[busy,setBusy]=useState(false),[tab,setTab]=useState("overview"),[scope,setScope]=useState("complex"),[form,setForm]=useState({fullName:"",email:"",password:"",positionKey:"",username:"",phone:""});
 const t={ru:{label:"Аккредитация",title:"Администрирование аккредитации",stats:"Закрытая статистика по аккредитации",createEmployee:"Регистрация нового сотрудника",create:"Создать аккаунт",requests:"Заявки на регистрацию",employees:"Зарегистрированные сотрудники",review:"Материалы на проверке",approve:"Принять",revision:"На доработку",confirm:"Подтвердить",reject:"Отклонить",position:"Должность",save:"Сохранить",disable:"Отключить",enable:"Включить",reset:"Сбросить доступ",remove:"Удалить",comment:"Комментарий проверяющего",created:"Аккаунт сотрудника создан.",owners:"ответственных подразделений и должностей",fullName:"Ф.И.О.",password:"Временный пароль (не менее 8 символов)",username:"Логин (латинскими буквами)",emailOptional:"Email для восстановления (необязательно)",phone:"Телефон (необязательно)",deleteConfirm:"Удалить сотрудника и его аккаунт?"},uz:{label:"Akkreditatsiya",title:"Akkreditatsiya administratsiyasi",stats:"Akkreditatsiya bo‘yicha yopiq statistika",createEmployee:"Yangi xodimni ro‘yxatdan o‘tkazish",create:"Akkaunt yaratish",requests:"Ro‘yxatdan o‘tish arizalari",employees:"Ro‘yxatdan o‘tgan xodimlar",review:"Tekshiruvdagi materiallar",approve:"Qabul qilish",revision:"Qayta ishlashga",confirm:"Tasdiqlash",reject:"Rad etish",position:"Lavozim",save:"Saqlash",disable:"O‘chirish",enable:"Yoqish",reset:"Kirishni bekor qilish",remove:"O‘chirish",comment:"Tekshiruvchi izohi",created:"Xodim akkaunti yaratildi.",owners:"mas’ul bo‘linma va lavozim",fullName:"F.I.Sh.",password:"Vaqtinchalik parol (kamida 8 ta belgi)",username:"Login (lotin harflarida)",emailOptional:"Tiklash uchun email (ixtiyoriy)",phone:"Telefon (ixtiyoriy)",deleteConfirm:"Xodim va uning akkaunti o‘chirilsinmi?"},en:{label:"Accreditation",title:"Accreditation administration",stats:"Private accreditation statistics",createEmployee:"Register a new employee",create:"Create account",requests:"Registration requests",employees:"Registered employees",review:"Materials under review",approve:"Approve",revision:"Return for revision",confirm:"Approve",reject:"Reject",position:"Position",save:"Save",disable:"Disable",enable:"Enable",reset:"Reset access",remove:"Delete",comment:"Reviewer comment",created:"Employee account created.",owners:"responsible units and positions",fullName:"Full name",password:"Temporary password (8+ characters)",username:"Username (Latin characters)",emailOptional:"Recovery email (optional)",phone:"Phone (optional)",deleteConfirm:"Delete the employee and their account?"}}[l];
 const load=useCallback(async()=>{const[{data:p},{data:i},{data:d},{data:s},{data:o}]=await Promise.all([supabase.from("accreditation_v3_profiles").select("*").order("created_at",{ascending:false}),supabase.from("accreditation_v3_indicators").select("id,code,status,completion_percent,responsible_label,responsible_user_id,project:accreditation_v3_projects(id,code)").in("status",["review","revision"]),supabase.from("accreditation_v3_documents").select("*").order("created_at",{ascending:false}),supabase.from("accreditation_v3_project_progress").select("*").order("project_code"),supabase.from("accreditation_v3_responsible_progress").select("*")]);setProfiles(p||[]);setItems(i||[]);setDocs(d||[]);setStats(s||[]);setOwners(o||[])},[supabase]); useEffect(()=>{void load()},[load]);
 async function createEmployee(e:React.FormEvent){e.preventDefault();setBusy(true);const p=positions.find(x=>x.key===form.positionKey),role=form.positionKey==="director"?"director":"department_head",r=await fetch("/api/admin/accreditation/users",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...form,jobTitle:p?positionLabel(p,l):"",role})}),j=await r.json();setBusy(false);if(!r.ok){setMsg(j.error||(l==="ru"?"Ошибка":l==="uz"?"Xato":"Error"));return}setForm({fullName:"",email:"",password:"",positionKey:"",username:"",phone:""});setMsg(t.created);void load()}
 async function update(p:Row,v:Row){if(v.approval_status==="approved"&&scope==="all"){setMsg(l==="ru"?"Перед подтверждением выберите конкретную аккредитацию.":l==="uz"?"Tasdiqlashdan oldin aniq akkreditatsiyani tanlang.":"Select a specific accreditation before approval.");return}const values=v.approval_status==="approved"&&p.requested_role==="director"?{...v,role:"director",position_key:"director"}:v;const{error}=await supabase.from("accreditation_v3_profiles").update(values).eq("user_id",p.user_id);if(!error&&v.approval_status==="approved"){const{data:project}=await supabase.from("accreditation_v3_projects").select("id").eq("code",scope).maybeSingle();const{data:{user}}=await supabase.auth.getUser();if(project)await supabase.from("accreditation_v72_user_project_access").upsert({user_id:p.user_id,project_id:project.id,access_role:values.role==="director"?"manager":"employee",granted_by:user?.id||null},{onConflict:"user_id,project_id"})}setMsg(error?.message||(l==="ru"?"Сохранено":l==="uz"?"Saqlandi":"Saved"));void load()}
 async function rpc(name:string,p:Row){if(name.includes("delete")&&!confirm(t.deleteConfirm))return;const{error}=await supabase.rpc(name,{target_user:p.user_id});setMsg(error?.message||(l==="ru"?"Сохранено":l==="uz"?"Saqlandi":"Saved"));void load()}
 async function review(id:string,decision:string){const{data:{user}}=await supabase.auth.getUser();if(!user)return;if(decision==="revision"&&!comments[id]?.trim()){setMsg(l==="ru"?"Укажите причину возврата на доработку.":l==="uz"?"Qayta ishlashga qaytarish sababini kiriting.":"Enter a reason for returning the response.");return}const text=comments[id]?.trim()||(l==="ru"?"Ответ принят":l==="uz"?"Javob qabul qilindi":"Response approved");const{error:r}=await supabase.from("accreditation_v3_reviews").insert({indicator_id:id,reviewer_id:user.id,decision,comment:text});if(r){setMsg(r.message);return}const{error}=await supabase.from("accreditation_v3_indicators").update({status:decision,completion_percent:decision==="approved"?100:50,approved_at:decision==="approved"?new Date().toISOString():null}).eq("id",id);setMsg(error?.message||(l==="ru"?"Сохранено":l==="uz"?"Saqlandi":"Saved"));void load()}
 async function openDoc(d:Row){const{data}=await supabase.storage.from("accreditation-v3-evidence").createSignedUrl(d.storage_path,300);if(data?.signedUrl)open(data.signedUrl,"_blank","noopener,noreferrer")}
 const scopedItems=scope==="all"?items:items.filter(x=>x.project?.code===scope),scopedStats=scope==="all"?stats:stats.filter(x=>x.project_code===scope);
 return <div className="space-y-7"><header><p className="text-sm font-black uppercase tracking-[.16em] text-cyan-700">{t.label}</p><h1 className="mt-2 text-4xl font-black">{t.title}</h1></header>{msg&&<p className="rounded-xl bg-blue-50 p-4 text-blue-800">{msg}</p>}<section className="rounded-2xl border border-blue-200 bg-blue-50 p-4"><label className="text-sm font-black">{l==="ru"?"Рабочая область аккредитации":l==="uz"?"Akkreditatsiya ish sohasi":"Accreditation workspace"}</label><select value={scope} onChange={e=>setScope(e.target.value)} className="mt-2 w-full rounded-xl border bg-white p-3"><option value="all">{l==="ru"?"Общая сводка":l==="uz"?"Umumiy hisobot":"Combined overview"}</option>{stats.map(x=><option key={x.project_code} value={x.project_code}>{projectLabel(x.project_code,l)}</option>)}</select></section><nav className="flex flex-wrap gap-2 rounded-2xl border bg-white p-3">{[["overview",l==="ru"?"Сводка":l==="uz"?"Umumiy":"Overview"],["employees",t.employees],["assignment",l==="ru"?"Назначения и сроки":l==="uz"?"Tayinlash va muddatlar":"Assignments"],["review",t.review]].map(([key,label])=><button key={key} onClick={()=>setTab(key)} className={`rounded-xl px-4 py-2 font-bold ${tab===key?"bg-blue-700 text-white":"bg-slate-100"}`}>{label}</button>)}</nav>
 {tab==="overview"&&<><AccreditationControlCenter locale={l} mode="admin" projectCode={scope}/><section className="rounded-[26px] border bg-white p-6 shadow-sm"><h2 className="text-2xl font-black">{t.stats}</h2><div className="mt-5 grid gap-4 md:grid-cols-3">{scopedStats.map(x=><article key={x.project_code} className="rounded-2xl bg-slate-50 p-5"><h3 className="font-bold">{l==="ru"?x.name_ru:l==="uz"?x.name_uz:x.name_en}</h3><b className="mt-3 block text-3xl text-blue-800">{x.progress}%</b><span className="text-sm text-slate-500">{x.approved}/{x.total}</span></article>)}</div><p className="mt-4 text-sm text-slate-500">{owners.length} {t.owners}</p></section></>}
 {tab==="assignment"&&<BulkAssignment locale={l} projectCode={scope}/>}
 {tab==="employees"&&<form onSubmit={createEmployee} className="rounded-[26px] border border-blue-100 bg-white p-6 shadow-sm"><h2 className="text-2xl font-black">{t.createEmployee}</h2><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3"><input required value={form.fullName} onChange={e=>setForm({...form,fullName:e.target.value})} placeholder={t.fullName} className="rounded-xl border px-4 py-3"/><input required pattern="[a-zA-Z0-9._-]{3,}" value={form.username} onChange={e=>setForm({...form,username:e.target.value.toLowerCase()})} placeholder={t.username} className="rounded-xl border px-4 py-3"/><input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder={t.emailOptional} className="rounded-xl border px-4 py-3"/><input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} placeholder={t.phone} className="rounded-xl border px-4 py-3"/><input required minLength={8} type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} placeholder={t.password} className="rounded-xl border px-4 py-3"/><select required value={form.positionKey} onChange={e=>setForm({...form,positionKey:e.target.value})} className="rounded-xl border bg-white px-4 py-3"><option value="">{t.position}</option>{positions.map(x=><option key={x.key} value={x.key}>{positionLabel(x,l)}</option>)}</select></div><button disabled={busy} className="mt-4 rounded-xl bg-blue-700 px-5 py-3 font-bold text-white">{busy?"...":t.create}</button></form>}
 {tab==="employees"&&<EmployeeAccountImport locale={l}/>}
 {tab==="employees"&&<section className="rounded-[26px] border bg-white p-6 shadow-sm"><h2 className="text-2xl font-black">{t.requests}</h2><div className="mt-5 space-y-3">{profiles.filter(p=>p.approval_status==="pending").map(p=><article key={p.user_id} className="rounded-2xl border border-amber-200 p-5"><b>{p.full_name}</b><p className="text-sm">{positionKeyLabel(p.position_key,p.job_title,l)}</p><p className="text-xs text-slate-500">{p.username||p.recovery_email||"—"}</p><div className="mt-3 flex gap-2"><button onClick={()=>void update(p,{role:"department_head",is_active:true,approval_status:"approved",approved_at:new Date().toISOString()})} className="rounded-lg bg-emerald-700 px-3 py-2 text-white">{t.confirm}</button><button onClick={()=>void update(p,{is_active:false,approval_status:"rejected"})} className="rounded-lg bg-red-100 px-3 py-2 text-red-700">{t.reject}</button></div></article>)}</div></section>}
 {tab==="employees"&&<section className="rounded-[26px] border bg-white p-6 shadow-sm"><h2 className="text-2xl font-black">{t.employees}</h2><div className="mt-5 space-y-3">{profiles.filter(p=>p.approval_status!=="pending").map(p=><article key={p.user_id} className="rounded-2xl border p-5"><div className="grid gap-4 xl:grid-cols-[1fr_1fr_auto] xl:items-center"><div><b>{p.full_name}</b><p className="text-sm">{positionKeyLabel(p.position_key,p.job_title,l)}</p><p className="text-xs text-slate-500">{p.username||p.recovery_email||"—"}</p></div><select value={drafts[p.user_id]??p.position_key??""} onChange={e=>setDrafts({...drafts,[p.user_id]:e.target.value})} className="rounded-xl border px-3 py-2">{positions.map(x=><option key={x.key} value={x.key}>{positionLabel(x,l)}</option>)}</select><div className="flex flex-wrap gap-2"><button onClick={()=>void update(p,{position_key:drafts[p.user_id]||p.position_key})} className="rounded-lg bg-blue-700 px-3 py-2 text-white">{t.save}</button><button onClick={()=>void update(p,{is_active:!p.is_active,approval_status:!p.is_active?"approved":"rejected"})} className="rounded-lg bg-slate-100 px-3 py-2">{p.is_active?t.disable:t.enable}</button><button onClick={()=>void rpc("accreditation_v5_reset_employee_access",p)} className="rounded-lg bg-red-100 px-3 py-2 text-red-700">{t.reset}</button><button onClick={()=>void rpc("accreditation_v57_delete_employee",p)} className="rounded-lg bg-red-700 px-3 py-2 text-white">{t.remove}</button></div></div>{p.is_active&&p.approval_status==="approved"&&p.role!=="director"&&<EmployeePositionManager locale={l} userId={p.user_id} primaryPosition={p.position_key}/>}</article>)}</div></section>}
 {tab==="review"&&<section className="rounded-[26px] border bg-white p-6 shadow-sm"><h2 className="text-2xl font-black">{t.review}</h2><div className="mt-5 space-y-4">{scopedItems.map(x=><article key={x.id} className="rounded-2xl border p-5"><b className="text-blue-700">{x.code}</b><p className="text-sm">{responsibleLabel(x.responsible_label,l)}</p><div className="mt-3 flex flex-wrap gap-2">{docs.filter(d=>d.indicator_id===x.id).map(d=><button key={d.id} onClick={()=>void openDoc(d)} className="rounded-lg bg-slate-50 px-3 py-2 text-blue-700">{d.file_name} · v{d.version}</button>)}</div><IndicatorCollaboration locale={l} indicatorId={x.id} assigneeId={x.responsible_user_id} canManage/><textarea value={comments[x.id]||""} onChange={e=>setComments({...comments,[x.id]:e.target.value})} placeholder={t.comment} className="mt-4 w-full rounded-xl border p-3"/><div className="mt-3 flex gap-2"><button onClick={()=>void review(x.id,"approved")} className="rounded-lg bg-emerald-700 px-3 py-2 text-white">{t.approve}</button><button onClick={()=>void review(x.id,"revision")} className="rounded-lg bg-red-100 px-3 py-2 text-red-700">{t.revision}</button></div></article>)}</div></section>}</div>;
}
