"use client";
import {useEffect,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase/client";
import type {Locale} from "@/lib/accreditation/specialData";
type Item={id:string;code:string;status:string;responsible_label:string;responsible_user_id:string|null;due_date:string|null;project:{code:string}|null};type Person={user_id:string;full_name:string;job_title:string};
export default function BulkAssignment({locale:l}:{locale:Locale}){
 const t={ru:{title:"Массовое назначение и сроки",search:"Код или подразделение",employee:"Выберите сотрудника",date:"Срок исполнения",assign:"Назначить",deadline:"Изменить только срок",select:"Выбрать результаты",clear:"Снять выбор",selected:"выбрано",project:"Все аккредитации",status:"Все статусы",unassigned:"Только неназначенные",all:"Все назначения",confirm:"Будет изменено индикаторов",done:"Обновлено индикаторов"},uz:{title:"Ommaviy tayinlash va muddatlar",search:"Kod yoki bo‘linma",employee:"Xodimni tanlang",date:"Bajarish muddati",assign:"Tayinlash",deadline:"Faqat muddatni o‘zgartirish",select:"Natijalarni tanlash",clear:"Tanlovni tozalash",selected:"tanlandi",project:"Barcha akkreditatsiyalar",status:"Barcha holatlar",unassigned:"Faqat biriktirilmagan",all:"Barcha tayinlovlar",confirm:"Indikatorlar o‘zgartiriladi",done:"Indikatorlar yangilandi"},en:{title:"Bulk assignment and deadlines",search:"Code or unit",employee:"Select employee",date:"Due date",assign:"Assign",deadline:"Change deadline only",select:"Select results",clear:"Clear selection",selected:"selected",project:"All accreditations",status:"All statuses",unassigned:"Unassigned only",all:"All assignments",confirm:"Indicators will be changed",done:"Indicators updated"}}[l];
 const s=useMemo(()=>createClient(),[]),[items,setItems]=useState<Item[]>([]),[people,setPeople]=useState<Person[]>([]),[selected,setSelected]=useState<string[]>([]),[q,setQ]=useState(""),[project,setProject]=useState("all"),[status,setStatus]=useState("all"),[assignment,setAssignment]=useState("all"),[user,setUser]=useState(""),[date,setDate]=useState(""),[priority,setPriority]=useState("normal"),[msg,setMsg]=useState(""),[busy,setBusy]=useState(false);
 async function load(){const[i,p]=await Promise.all([s.from("accreditation_v3_indicators").select("id,code,status,responsible_label,responsible_user_id,due_date,project:accreditation_v3_projects(code)").order("code"),s.from("accreditation_v3_profiles").select("user_id,full_name,job_title").eq("approval_status","approved").eq("is_active",true).order("full_name")]);setItems((i.data||[]) as unknown as Item[]);setPeople((p.data||[]) as Person[])}
 useEffect(()=>{void load()},[]);
 const shown=items.filter(x=>(!q||`${x.code} ${x.responsible_label}`.toLowerCase().includes(q.toLowerCase()))&&(project==='all'||x.project?.code===project)&&(status==='all'||x.status===status)&&(assignment==='all'||!x.responsible_user_id)),projects=Array.from(new Set(items.map(x=>x.project?.code).filter(Boolean))) as string[];
 function chooseAll(){setSelected(Array.from(new Set([...selected,...shown.map(x=>x.id)])))}
 async function apply(kind:"assign"|"deadline"){if(!selected.length||!date&&kind==='deadline'||!user&&kind==='assign')return;if(!confirm(`${t.confirm}: ${selected.length}`))return;setBusy(true);const response=kind==='assign'?await s.rpc("accreditation_v6_bulk_assign",{target_user:user,indicator_ids:selected,target_due_date:date||null,target_priority:priority}):await s.rpc("accreditation_v6_set_deadlines",{indicator_ids:selected,target_due_date:date,target_priority:priority});setBusy(false);setMsg(response.error?.message||`${t.done}: ${response.data}`);if(!response.error){setSelected([]);void load()}}
 return <section className="rounded-[26px] border bg-white p-6 shadow-sm"><h2 className="text-2xl font-black">{t.title}</h2>{msg&&<p className="mt-3 rounded-xl bg-blue-50 p-3 text-blue-800">{msg}</p>}<div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4"><input value={q} onChange={e=>setQ(e.target.value)} placeholder={t.search} className="rounded-xl border p-3"/><select value={project} onChange={e=>setProject(e.target.value)} className="rounded-xl border p-3"><option value="all">{t.project}</option>{projects.map(x=><option key={x}>{x}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)} className="rounded-xl border p-3"><option value="all">{t.status}</option>{["draft","in_progress","review","revision","approved"].map(x=><option key={x}>{x}</option>)}</select><select value={assignment} onChange={e=>setAssignment(e.target.value)} className="rounded-xl border p-3"><option value="all">{t.all}</option><option value="unassigned">{t.unassigned}</option></select><select value={user} onChange={e=>setUser(e.target.value)} className="rounded-xl border p-3"><option value="">{t.employee}</option>{people.map(x=><option key={x.user_id} value={x.user_id}>{x.full_name} — {x.job_title}</option>)}</select><input type="date" value={date} onChange={e=>setDate(e.target.value)} aria-label={t.date} className="rounded-xl border p-3"/><select value={priority} onChange={e=>setPriority(e.target.value)} className="rounded-xl border p-3">{["low","normal","high","critical"].map(x=><option key={x}>{x}</option>)}</select></div><div className="mt-3 flex flex-wrap gap-2"><button onClick={chooseAll} className="rounded-xl bg-slate-100 px-4 py-2 font-bold">{t.select} ({shown.length})</button><button onClick={()=>setSelected([])} className="rounded-xl bg-slate-100 px-4 py-2 font-bold">{t.clear}</button><button onClick={()=>void apply('assign')} disabled={busy||!user||!selected.length} className="rounded-xl bg-blue-700 px-4 py-2 font-bold text-white disabled:opacity-40">{t.assign} ({selected.length})</button><button onClick={()=>void apply('deadline')} disabled={busy||!date||!selected.length} className="rounded-xl bg-amber-600 px-4 py-2 font-bold text-white disabled:opacity-40">{t.deadline}</button></div><div className="mt-4 max-h-[520px] space-y-2 overflow-auto">{shown.map(x=><label key={x.id} className="grid cursor-pointer gap-2 rounded-xl border p-3 md:grid-cols-[30px_100px_160px_1fr_120px]"><input type="checkbox" checked={selected.includes(x.id)} onChange={e=>setSelected(e.target.checked?Array.from(new Set([...selected,x.id])):selected.filter(id=>id!==x.id))}/><b>{x.code}</b><span>{x.project?.code}</span><span className="text-sm text-slate-600">{x.responsible_label}</span><span className="text-sm">{x.due_date||'—'}</span></label>)}</div></section>
}
