"use client";
import {useEffect,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase/client";
import type {Locale} from "@/lib/accreditation/specialData";
type Risk={id:string;code:string;status:string;completion_percent:number;due_date:string|null;priority:string;responsible_label:string;full_name:string|null;project_code:string;overdue:boolean;days_left:number|null};
type Audit={id:string;code:string;project_code:string;actor_name:string;action:string;created_at:string};
export default function DirectorOperations({locale:l}:{locale:Locale}){
 const t={ru:{title:"Операционный контроль",risk:"Зона риска",log:"Журнал действий",all:"Все",owner:"Ответственный",status:"Статус",deadline:"Срок",overdue:"Просрочено",soon:"До 7 дней",none:"Без срока",excel:"Экспорт Excel",pdf:"Экспорт PDF",health:"Проверить доступность",backup:"Создать резервный снимок",ok:"Сайт и база доступны",project:"Аккредитация"},uz:{title:"Operatsion nazorat",risk:"Xavf zonasi",log:"Harakatlar jurnali",all:"Barchasi",owner:"Mas’ul",status:"Holat",deadline:"Muddat",overdue:"Muddati o‘tgan",soon:"7 kungacha",none:"Muddatsiz",excel:"Excel eksporti",pdf:"PDF eksporti",health:"Mavjudlikni tekshirish",backup:"Zaxira nusxasini yaratish",ok:"Sayt va baza ishlamoqda",project:"Akkreditatsiya"},en:{title:"Operational control",risk:"Risk zone",log:"Activity log",all:"All",owner:"Owner",status:"Status",deadline:"Deadline",overdue:"Overdue",soon:"Within 7 days",none:"No deadline",excel:"Export Excel",pdf:"Export PDF",health:"Check availability",backup:"Create backup snapshot",ok:"Site and database are available",project:"Accreditation"}}[l];
 const s=useMemo(()=>createClient(),[]),[risks,setRisks]=useState<Risk[]>([]),[audit,setAudit]=useState<Audit[]>([]),[tab,setTab]=useState<"risk"|"log">("risk"),[unit,setUnit]=useState("all"),[owner,setOwner]=useState("all"),[status,setStatus]=useState("all"),[deadline,setDeadline]=useState("all"),[message,setMessage]=useState("");
 useEffect(()=>{void Promise.all([s.from("accreditation_v6_risk").select("*").order("due_date",{ascending:true,nullsFirst:false}),s.from("accreditation_v6_audit_log").select("*").order("created_at",{ascending:false}).limit(500)]).then(([r,a])=>{setRisks((r.data||[]) as Risk[]);setAudit((a.data||[]) as Audit[])})},[s]);
 const owners=Array.from(new Set(risks.map(x=>x.full_name||x.responsible_label).filter(Boolean))).sort(),filtered=risks.filter(x=>(unit==="all"||x.project_code===unit)&&(owner==="all"||(x.full_name||x.responsible_label)===owner)&&(status==="all"||x.status===status)&&(deadline==="all"||(deadline==="overdue"&&x.overdue)||(deadline==="soon"&&!x.overdue&&x.days_left!==null&&x.days_left<=7)||(deadline==="none"&&!x.due_date))),rows=filtered.map(x=>({Code:x.code,Project:x.project_code,Owner:x.full_name||x.responsible_label,Status:x.status,Progress:`${x.completion_percent}%`,Deadline:x.due_date||"",Priority:x.priority,Overdue:x.overdue?"YES":""}));
 async function excel(){const X=await import("xlsx"),ws=X.utils.json_to_sheet(rows),wb=X.utils.book_new();X.utils.book_append_sheet(wb,ws,"Risk zone");X.writeFile(wb,"director-risk-zone.xlsx")}
 async function pdf(){const{jsPDF}=await import("jspdf"),d=new jsPDF({orientation:"landscape"}),buf=await fetch("/DejaVuSans.ttf").then(r=>r.arrayBuffer());let bin="";new Uint8Array(buf).forEach(b=>bin+=String.fromCharCode(b));d.addFileToVFS("DejaVuSans.ttf",btoa(bin));d.addFont("DejaVuSans.ttf","DejaVu","normal");d.setFont("DejaVu");d.setFontSize(14);d.text(t.risk,12,14);d.setFontSize(8);let y=22;for(const x of filtered){d.text(`${x.code} | ${x.project_code} | ${x.full_name||x.responsible_label||"—"} | ${x.status} | ${x.due_date||"—"}${x.overdue?` | ${t.overdue}`:""}`,12,y);y+=6;if(y>195){d.addPage();d.setFont("DejaVu");y=14}}d.save("director-risk-zone.pdf")}
 async function health(){const{data,error}=await s.rpc("accreditation_v6_health");setMessage(error?.message||`${t.ok}: ${data?.indicators||0}`)}async function backup(){const{data,error}=await s.rpc("accreditation_v6_create_snapshot",{snapshot_reason:"manual-director"});setMessage(error?.message||`Backup #${data}`)}
 return <section className="rounded-[28px] border border-slate-200 bg-white p-6 shadow-sm"><div className="flex flex-wrap justify-between gap-3"><h2 className="text-2xl font-black">{t.title}</h2><div className="flex gap-2"><button onClick={()=>void health()} className="rounded-xl bg-slate-100 px-3 py-2 text-sm font-bold">{t.health}</button><button onClick={()=>void backup()} className="rounded-xl bg-slate-900 px-3 py-2 text-sm font-bold text-white">{t.backup}</button></div></div>{message&&<p className="mt-3 rounded-xl bg-blue-50 p-3 text-blue-800">{message}</p>}<div className="mt-5 flex gap-2"><button onClick={()=>setTab("risk")} className={`rounded-xl px-4 py-2 font-bold ${tab==="risk"?"bg-red-700 text-white":"bg-slate-100"}`}>{t.risk} ({risks.filter(x=>x.overdue).length})</button><button onClick={()=>setTab("log")} className={`rounded-xl px-4 py-2 font-bold ${tab==="log"?"bg-blue-700 text-white":"bg-slate-100"}`}>{t.log}</button></div>
 {tab==="risk"?<><div className="mt-4 grid gap-3 md:grid-cols-4"><select value={unit} onChange={e=>setUnit(e.target.value)} className="rounded-xl border p-3"><option value="all">{t.project}: {t.all}</option>{Array.from(new Set(risks.map(x=>x.project_code))).map(x=><option key={x}>{x}</option>)}</select><select value={owner} onChange={e=>setOwner(e.target.value)} className="rounded-xl border p-3"><option value="all">{t.owner}: {t.all}</option>{owners.map(x=><option key={x}>{x}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)} className="rounded-xl border p-3"><option value="all">{t.status}: {t.all}</option>{["draft","in_progress","review","revision","approved"].map(x=><option key={x}>{x}</option>)}</select><select value={deadline} onChange={e=>setDeadline(e.target.value)} className="rounded-xl border p-3"><option value="all">{t.deadline}: {t.all}</option><option value="overdue">{t.overdue}</option><option value="soon">{t.soon}</option><option value="none">{t.none}</option></select></div><div className="mt-3 flex gap-2"><button onClick={()=>void excel()} className="rounded-xl bg-emerald-700 px-4 py-2 font-bold text-white">{t.excel}</button><button onClick={()=>void pdf()} className="rounded-xl bg-red-700 px-4 py-2 font-bold text-white">{t.pdf}</button></div><div className="mt-5 max-h-[650px] space-y-2 overflow-auto">{filtered.slice(0,300).map(x=><article key={x.id} className={`grid gap-2 rounded-xl border p-4 md:grid-cols-[110px_1fr_150px_110px] ${x.overdue?"border-red-300 bg-red-50":""}`}><b>{x.code}</b><span>{x.full_name||x.responsible_label||"—"}</span><span>{x.status} · {x.completion_percent}%</span><span className={x.overdue?"font-bold text-red-700":""}>{x.due_date||t.none}</span></article>)}</div></>:<div className="mt-5 max-h-[650px] space-y-2 overflow-auto">{audit.map(x=><article key={x.id} className="grid gap-2 rounded-xl border p-4 md:grid-cols-[160px_110px_1fr_150px]"><time>{new Date(x.created_at).toLocaleString(l)}</time><b>{x.code}</b><span>{x.actor_name} · {x.action}</span><span>{x.project_code}</span></article>)}</div>}</section>
}
