"use client";
import {useEffect,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase/client";
import type {Locale} from "@/lib/accreditation/specialData";
import IndicatorCollaboration from "./IndicatorCollaboration";
import {projectLabel,responsibleLabel} from "@/lib/accreditation/localization";
type Risk={id:string;code:string;responsible_user_id:string|null;status:string;completion_percent:number;full_name:string|null;responsible_label:string;overdue:boolean;project_code:string};type Snap={id:number;created_at:string;payload:{indicators?:Array<{status:string;completion_percent:number;project_id?:string}>}};
export default function DirectorV7Insights({locale:l,projectCode="all"}:{locale:Locale;projectCode?:string}){const s=useMemo(()=>createClient(),[]),[allRows,setRows]=useState<Risk[]>([]),[snaps,setSnaps]=useState<Snap[]>([]),[projectId,setProjectId]=useState<string|null>(null),[presentation,setPresentation]=useState(false),[selected,setSelected]=useState(""),[now]=useState(()=>new Date());const t={ru:{title:"Динамика и управленческие риски",week:"Изменение за неделю",snapshot:"С предыдущего снимка",problem:"Пять проблемных подразделений",overdue:"Лидеры по просрочкам",presentation:"Режим презентации",exit:"Закрыть презентацию",approved:"принято",noData:"Недостаточно данных для сравнения"},uz:{title:"Dinamika va boshqaruv xavflari",week:"Haftalik o‘zgarish",snapshot:"Oldingi nusxadan",problem:"Beshta muammoli bo‘linma",overdue:"Kechikishlar bo‘yicha yetakchilar",presentation:"Taqdimot rejimi",exit:"Taqdimotni yopish",approved:"qabul qilindi",noData:"Taqqoslash uchun ma’lumot yetarli emas"},en:{title:"Trends and management risks",week:"Weekly change",snapshot:"Since previous snapshot",problem:"Five units at highest risk",overdue:"Most overdue assignments",presentation:"Presentation mode",exit:"Close presentation",approved:"approved",noData:"Not enough comparison data"}}[l];useEffect(()=>{let active=true;(async()=>{const[r,b,p]=await Promise.all([s.from("accreditation_v6_risk").select("id,code,responsible_user_id,status,completion_percent,full_name,responsible_label,overdue,project_code"),s.from("accreditation_v6_snapshots").select("id,created_at,payload").order("created_at",{ascending:false}).limit(10),projectCode==="all"?Promise.resolve({data:null}):s.from("accreditation_v3_projects").select("id").eq("code",projectCode).maybeSingle()]);if(active){setRows((r.data||[]) as Risk[]);setSnaps((b.data||[]) as Snap[]);setProjectId(p.data?.id||null)}})();return()=>{active=false}},[s,projectCode]);
 const rows=projectCode==="all"?allRows:allRows.filter(x=>x.project_code===projectCode),snapshotRows=(items:NonNullable<Snap["payload"]["indicators"]>)=>projectId?items.filter(x=>x.project_id===projectId):items;
 const grouped=(filter:(x:Risk)=>boolean)=>{const m=new Map<string,Risk[]>();rows.filter(filter).forEach(x=>{const k=x.full_name||responsibleLabel(x.responsible_label,l)||"—";m.set(k,[...(m.get(k)||[]),x])});return[...m].map(([name,list])=>({name,total:list.length,overdue:list.filter(x=>x.overdue).length,score:Math.round(list.reduce((a,x)=>a+x.completion_percent,0)/list.length)})).sort((a,b)=>a.score-b.score||b.overdue-a.overdue).slice(0,5)};const problems=grouped(()=>true),late=grouped(x=>x.overdue).sort((a,b)=>b.overdue-a.overdue);const approved=rows.filter(x=>x.status==="approved").length,currentProgress=rows.length?Math.round(rows.reduce((a,x)=>a+x.completion_percent,0)/rows.length):0,previous=snapshotRows(snaps[1]?.payload?.indicators||[]),previousProgress=previous.length?Math.round(previous.reduce((a,x)=>a+Number(x.completion_percent||0),0)/previous.length):null,week=snapshotRows(snaps.find(x=>now.getTime()-new Date(x.created_at).getTime()>=6*86400000)?.payload?.indicators||[]),weekApproved=week.filter(x=>x.status==="approved").length;
 const body=<section className={`${presentation?"fixed inset-0 z-[100] overflow-auto bg-slate-950 p-5 text-white sm:p-10":"rounded-[28px] border bg-white p-4 shadow-sm sm:p-6"}`}><div className="flex flex-wrap justify-between gap-3"><h2 className="text-2xl font-black">{t.title}</h2><button onClick={()=>setPresentation(x=>!x)} className={`rounded-xl px-4 py-2 font-bold ${presentation?"bg-white text-slate-900":"bg-slate-900 text-white"}`}>{presentation?t.exit:t.presentation}</button></div><div className="mt-5 grid gap-3 sm:grid-cols-3"><article className="rounded-2xl bg-blue-700 p-5 text-white"><b className="text-4xl">{currentProgress}%</b><p>{approved} {t.approved}</p></article><article className="rounded-2xl bg-emerald-700 p-5 text-white"><b className="text-4xl">{week.length?`${approved-weekApproved>=0?"+":""}${approved-weekApproved}`:"—"}</b><p>{t.week}</p></article><article className="rounded-2xl bg-violet-700 p-5 text-white"><b className="text-4xl">{previousProgress===null?"—":`${currentProgress-previousProgress>=0?"+":""}${currentProgress-previousProgress}%`}</b><p>{t.snapshot}</p></article></div>{!snaps.length&&<p className="mt-3 text-slate-500">{t.noData}</p>}<div className="mt-5 grid gap-5 lg:grid-cols-2"><List title={t.problem} rows={problems} dark={presentation}/><List title={t.overdue} rows={late} dark={presentation}/></div><div className="mt-5 rounded-2xl border border-white/20 p-4"><select value={selected} onChange={e=>setSelected(e.target.value)} className="w-full rounded-xl border bg-white p-3 text-slate-900"><option value="">{l==='ru'?'Выберите индикатор для поручения':l==='uz'?'Topshiriq uchun indikatorni tanlang':'Select indicator for assignment'}</option>{rows.map(x=><option key={x.id} value={x.id}>{projectLabel(x.project_code,l)} · {x.code} · {x.full_name||responsibleLabel(x.responsible_label,l)}</option>)}</select>{selected&&<IndicatorCollaboration locale={l} indicatorId={selected} assigneeId={rows.find(x=>x.id===selected)?.responsible_user_id||null} canManage/>}</div></section>;return body}
function List({title,rows,dark}:{title:string;rows:Array<{name:string;total:number;overdue:number;score:number}>;dark:boolean}){return <div className={`rounded-2xl border p-5 ${dark?"border-white/20 bg-white/10":"bg-slate-50"}`}><h3 className="font-black">{title}</h3><div className="mt-3 space-y-2">{rows.map((x,i)=><div key={x.name} className="grid grid-cols-[28px_1fr_auto] gap-2 rounded-xl bg-white/10 p-3"><b>{i+1}</b><span>{x.name}</span><span className="font-bold">{x.score}% · {x.overdue}</span></div>)}</div></div>}
