"use client";

import { useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import type { Locale } from "@/lib/accreditation/specialData";
import { accreditationUi } from "@/lib/accreditation/ui";
import DirectorOperations from "./DirectorOperations";
import AccreditationControlCenter from "./AccreditationControlCenter";
import DirectorV7Insights from "./DirectorV7Insights";

type ProjectRow = { project_code:string; name_ru:string; name_uz:string; name_en:string; total:number; approved:number; review:number; revision:number; in_progress:number; draft:number; progress:number };
type ResponsibleRow = { responsible_label:string; total:number; approved:number; review:number; revision:number; in_progress:number; draft:number; progress:number };

export default function DirectorDashboard({ locale:l }: { locale:Locale }) {
  const t=accreditationUi[l]; const supabase=useMemo(()=>createClient(),[]);
  const [profile,setProfile]=useState<any>(null); const [rows,setRows]=useState<ProjectRow[]>([]); const [owners,setOwners]=useState<ResponsibleRow[]>([]); const [loading,setLoading]=useState(true);
  useEffect(()=>{let active=true; async function load(){const {data:{user}}=await supabase.auth.getUser();if(!user){location.href=`/${l}/accreditation/login`;return} const {data:p}=await supabase.from("accreditation_v3_profiles").select("*").eq("user_id",user.id).maybeSingle();if(active)setProfile(p);if(!p||p.role!=="director"){setLoading(false);return} const [{data:r},{data:o}]=await Promise.all([supabase.from("accreditation_v3_project_progress").select("*").order("project_code"),supabase.from("accreditation_v3_responsible_progress").select("*").order("progress")]);if(active){setRows((r||[]) as ProjectRow[]);setOwners((o||[]) as ResponsibleRow[])}setLoading(false)} void load();const c=supabase.channel("director-accreditation-v3").on("postgres_changes",{event:"*",schema:"public",table:"accreditation_v3_indicators"},()=>void load()).subscribe();return()=>{active=false;void supabase.removeChannel(c)}},[supabase,l]);
  if(loading)return <div className="p-10">...</div>; if(!profile||profile.role!=="director")return <div className="rounded-2xl bg-red-50 p-6 text-red-800">{l==='ru'?'Доступ к кабинету директора не назначен.':l==='uz'?'Direktor kabinetiga kirish huquqi berilmagan.':'Director dashboard access has not been assigned.'}</div>;
  const total=rows.reduce((a,x)=>a+Number(x.total||0),0),approved=rows.reduce((a,x)=>a+Number(x.approved||0),0),review=rows.reduce((a,x)=>a+Number(x.review||0),0),revision=rows.reduce((a,x)=>a+Number(x.revision||0),0),progress=total?Math.round(rows.reduce((a,x)=>a+Number(x.progress||0)*Number(x.total||0),0)/total):0;
  const tx={ru:{streams:'Мониторинг по видам аккредитации',owners:'Мониторинг по ответственным подразделениям',notStarted:'Не начато',work:'В работе'},uz:{streams:'Akkreditatsiya turlari bo‘yicha monitoring',owners:'Mas’ul bo‘linmalar bo‘yicha monitoring',notStarted:'Boshlanmagan',work:'Jarayonda'},en:{streams:'Monitoring by accreditation stream',owners:'Monitoring by responsible unit',notStarted:'Not started',work:'In progress'}}[l];
  return <div className="space-y-6"><section className="rounded-[30px] bg-gradient-to-br from-[#0f5fa8] to-[#22a1a5] p-8 text-white"><p className="text-sm font-bold uppercase tracking-wider">{profile.job_title||'Director'}</p><h1 className="mt-2 text-4xl font-black">{t.director}</h1><p className="mt-2 text-blue-50">{profile.full_name}</p></section>
  <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{[[t.readiness,`${progress}%`],[t.total,total],[t.approved,approved],[t.review,review],[t.revision,revision]].map(([a,b])=><article key={String(a)} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="text-3xl font-black text-slate-900">{b}</div><div className="mt-1 text-sm text-slate-500">{a}</div></article>)}</section>
  <AccreditationControlCenter locale={l} mode="director"/>
  <DirectorV7Insights locale={l}/>
  <section className="rounded-[28px] border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-2xl font-black text-slate-900">{tx.streams}</h2><div className="mt-5 space-y-4">{rows.map(x=><article key={x.project_code} className="rounded-2xl border border-slate-200 p-5"><div className="flex items-center justify-between gap-4"><div><h3 className="font-bold text-slate-900">{l==='ru'?x.name_ru:l==='uz'?x.name_uz:x.name_en}</h3><p className="mt-1 text-sm text-slate-500">{x.approved} {t.approved.toLowerCase()} · {x.review} {t.review.toLowerCase()} · {x.revision} {t.revision.toLowerCase()}</p></div><div className="text-2xl font-black text-blue-800">{x.progress}%</div></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full bg-gradient-to-r from-blue-600 to-cyan-500" style={{width:`${x.progress}%`}}/></div></article>)}</div></section>
  <DirectorOperations locale={l}/>
  <section className="rounded-[28px] border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-2xl font-black text-slate-900">{tx.owners}</h2><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[850px] text-left"><thead className="border-b text-xs uppercase text-slate-500"><tr><th className="pb-3">{t.responsible}</th><th className="pb-3">{t.total}</th><th className="pb-3">{t.approved}</th><th className="pb-3">{t.review}</th><th className="pb-3">{t.revision}</th><th className="pb-3">{tx.work}</th><th className="pb-3">{tx.notStarted}</th><th className="pb-3">%</th></tr></thead><tbody>{owners.map(x=><tr key={x.responsible_label} className="border-b border-slate-100"><td className="py-4 pr-4 font-semibold">{x.responsible_label}</td><td>{x.total}</td><td className="text-emerald-700">{x.approved}</td><td className="text-amber-700">{x.review}</td><td className="text-red-700">{x.revision}</td><td>{x.in_progress}</td><td>{x.draft}</td><td className="font-black text-blue-800">{x.progress}%</td></tr>)}</tbody></table></div></section></div>;
}
