"use client";
import {useCallback,useEffect,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase/client";
import {accreditationPositions,positionLabel} from "@/lib/accreditation/positions";
import {projectLabel} from "@/lib/accreditation/localization";
import type {Locale} from "@/lib/accreditation/specialData";

type Project={id:string;code:string};
type Assignment={id:string;position_key:string;project_id:string;project:Project|null};
type Preview={free:number;conflicts:number;already:number}|null;
const matchKey=(key:string)=>key.startsWith("department_head_")?"department_head":key;

export default function EmployeePositionManager({locale:l,userId,primaryPosition}:{locale:Locale;userId:string;primaryPosition:string|null}){
 const s=useMemo(()=>createClient(),[]),[projects,setProjects]=useState<Project[]>([]),[roles,setRoles]=useState<Assignment[]>([]),[projectId,setProjectId]=useState(""),[positionKey,setPositionKey]=useState(""),[preview,setPreview]=useState<Preview>(null),[busy,setBusy]=useState(false),[msg,setMsg]=useState("");
 const t={ru:{title:"Закреплённые роли",primary:"Основная должность",additional:"Дополнительные роли",add:"Добавить роль",chooseProject:"Выберите аккредитацию",chooseRole:"Выберите дополнительную роль",preview:"Предварительная проверка",free:"будет назначено",conflicts:"занято другими сотрудниками",already:"уже закреплено за сотрудником",remove:"Снять роль",none:"Дополнительных ролей нет",confirm:"Назначить роль? Занятые другим сотрудником индикаторы не будут изменены.",saved:"Роль назначена",removed:"Роль снята"},uz:{title:"Biriktirilgan rollar",primary:"Asosiy lavozim",additional:"Qo‘shimcha rollar",add:"Rol qo‘shish",chooseProject:"Akkreditatsiyani tanlang",chooseRole:"Qo‘shimcha rolni tanlang",preview:"Dastlabki tekshiruv",free:"biriktiriladi",conflicts:"boshqa xodimlarga biriktirilgan",already:"xodimga avval biriktirilgan",remove:"Rolni olib tashlash",none:"Qo‘shimcha rollar yo‘q",confirm:"Rol biriktirilsinmi? Boshqa xodim band qilgan indikatorlar o‘zgarmaydi.",saved:"Rol biriktirildi",removed:"Rol olib tashlandi"},en:{title:"Assigned roles",primary:"Primary position",additional:"Additional roles",add:"Add role",chooseProject:"Select accreditation",chooseRole:"Select an additional role",preview:"Validation preview",free:"will be assigned",conflicts:"assigned to other employees",already:"already assigned to this employee",remove:"Remove role",none:"No additional roles",confirm:"Assign this role? Indicators owned by other employees will remain unchanged.",saved:"Role assigned",removed:"Role removed"}}[l];
 const load=useCallback(async()=>{const[p,r]=await Promise.all([s.from("accreditation_v3_projects").select("id,code").order("code"),s.from("accreditation_v73_employee_positions").select("id,position_key,project_id,project:accreditation_v3_projects(id,code)").eq("user_id",userId).eq("is_active",true).order("assigned_at")]);setProjects((p.data||[]) as Project[]);setRoles((r.data||[]) as unknown as Assignment[])},[s,userId]);
 useEffect(()=>{let active=true;void Promise.all([s.from("accreditation_v3_projects").select("id,code").order("code"),s.from("accreditation_v73_employee_positions").select("id,position_key,project_id,project:accreditation_v3_projects(id,code)").eq("user_id",userId).eq("is_active",true).order("assigned_at")]).then(([p,r])=>{if(active){setProjects((p.data||[]) as Project[]);setRoles((r.data||[]) as unknown as Assignment[])}});return()=>{active=false}},[s,userId]);
 useEffect(()=>{if(!projectId||!positionKey)return;let active=true;(async()=>{const{data}=await s.from("accreditation_v3_indicators").select("responsible_user_id").eq("project_id",projectId).contains("position_keys",[matchKey(positionKey)]);if(active){const rows=data||[];setPreview({free:rows.filter(x=>!x.responsible_user_id).length,conflicts:rows.filter(x=>x.responsible_user_id&&x.responsible_user_id!==userId).length,already:rows.filter(x=>x.responsible_user_id===userId).length})}})();return()=>{active=false}},[s,projectId,positionKey,userId]);
 async function add(){if(!projectId||!positionKey||!confirm(t.confirm))return;setBusy(true);setMsg("");const{data,error}=await s.rpc("accreditation_v73_add_position",{target_user:userId,target_project:projectId,target_position:positionKey});setBusy(false);if(error){setMsg(error.message);return}const result=data as {assigned?:number;conflicts?:number};setMsg(`${t.saved}: ${result.assigned||0}; ${t.conflicts}: ${result.conflicts||0}`);setPositionKey("");setPreview(null);void load()}
 async function remove(role:Assignment){const position=accreditationPositions.find(x=>x.key===role.position_key),label=position?positionLabel(position,l):role.position_key;if(!confirm(`${t.remove}: ${label}?`))return;setBusy(true);const{error}=await s.rpc("accreditation_v73_remove_position",{target_position_id:role.id});setBusy(false);setMsg(error?.message||t.removed);if(!error)void load()}
 const primary=accreditationPositions.find(x=>x.key===primaryPosition);
 return <div className="mt-4 min-w-0 overflow-hidden rounded-2xl border border-blue-100 bg-blue-50/40 p-4"><h3 className="font-black text-slate-900">{t.title}</h3><p className="mt-2 break-words text-sm"><span className="font-bold text-slate-500">{t.primary}:</span> {primary?positionLabel(primary,l):primaryPosition||"—"}</p><div className="mt-3 flex min-w-0 flex-wrap gap-2">{roles.map(role=>{const p=accreditationPositions.find(x=>x.key===role.position_key);return <span key={role.id} className="inline-flex max-w-full items-center gap-2 rounded-xl bg-white px-3 py-2 text-sm ring-1 ring-blue-100"><b className="min-w-0 break-words">{p?positionLabel(p,l):role.position_key}</b><span className="min-w-0 break-words text-slate-500">· {projectLabel(role.project?.code||"",l)}</span><button disabled={busy} onClick={()=>void remove(role)} className="shrink-0 font-black text-red-700" title={t.remove}>×</button></span>})}{!roles.length&&<span className="text-sm text-slate-500">{t.none}</span>}</div><div className="mt-4 grid min-w-0 gap-2 xl:grid-cols-2"><select value={projectId} onChange={e=>setProjectId(e.target.value)} className="min-w-0 w-full rounded-xl border bg-white p-3"><option value="">{t.chooseProject}</option>{projects.map(x=><option key={x.id} value={x.id}>{projectLabel(x.code,l)}</option>)}</select><select value={positionKey} onChange={e=>setPositionKey(e.target.value)} className="min-w-0 w-full rounded-xl border bg-white p-3"><option value="">{t.chooseRole}</option>{accreditationPositions.filter(x=>x.key!=="director"&&x.key!==primaryPosition).map(x=><option key={x.key} value={x.key}>{positionLabel(x,l)}</option>)}</select><button disabled={busy||!projectId||!positionKey} onClick={()=>void add()} className="w-full rounded-xl bg-blue-700 px-4 py-3 text-center font-bold text-white disabled:opacity-40 xl:col-span-2">{busy?"…":t.add}</button></div>{preview&&<div className="mt-3 break-words rounded-xl bg-white p-3 text-sm"><b>{t.preview}:</b> <span className="text-emerald-700">{preview.free} {t.free}</span> · <span className="text-red-700">{preview.conflicts} {t.conflicts}</span> · {preview.already} {t.already}</div>}{msg&&<p className="mt-3 break-words text-sm font-semibold text-blue-800">{msg}</p>}</div>
}
