"use client";

import { useEffect, useState } from "react";
import type { Locale } from "@/lib/accreditation/specialData";

export default function EmployeeEvidenceAssistant({locale:l,indicatorId,hasFile}:{locale:Locale;indicatorId:string;hasFile:boolean}){
  const key=`accreditation-draft-${indicatorId}`,[ready,setReady]=useState(false),[checks,setChecks]=useState([false,false,false]),[note,setNote]=useState("");
  const tx={ru:{title:"Проверка готовности ответа",checks:["Документ соответствует требованию индикатора","В файле указаны дата, подразделение и ответственный","Файл читается и не содержит лишних персональных данных"],note:"Черновик пояснения к ответу",saved:"Черновик автоматически сохранён на этом устройстве",readiness:"Готовность"},uz:{title:"Javob tayyorligini tekshirish",checks:["Hujjat indikator talabiga mos","Faylda sana, bo‘linma va mas’ul ko‘rsatilgan","Fayl o‘qiladi va ortiqcha shaxsiy ma’lumot yo‘q"],note:"Javob izohi qoralamasi",saved:"Qoralama ushbu qurilmada avtomatik saqlandi",readiness:"Tayyorlik"},en:{title:"Response readiness check",checks:["Document matches the indicator requirement","Date, unit and owner are stated in the file","File is readable and contains no unnecessary personal data"],note:"Draft response note",saved:"Draft is saved automatically on this device",readiness:"Readiness"}}[l];
  useEffect(()=>{try{const v=JSON.parse(localStorage.getItem(key)||"{}");setChecks(Array.isArray(v.checks)?v.checks:[false,false,false]);setNote(typeof v.note==="string"?v.note:"")}catch{}setReady(true)},[key]);
  useEffect(()=>{if(ready)localStorage.setItem(key,JSON.stringify({checks,note,updatedAt:new Date().toISOString()}))},[ready,key,checks,note]);
  const complete=checks.filter(Boolean).length+(hasFile?1:0),percent=Math.round(complete/4*100);
  return <details className="mt-3 rounded-xl border border-slate-200 bg-white"><summary className="cursor-pointer list-none p-3 font-bold text-slate-800"><span className="flex items-center justify-between gap-3"><span>{tx.title}</span><span className={`rounded-full px-3 py-1 text-xs ${percent===100?"bg-emerald-100 text-emerald-800":"bg-amber-100 text-amber-900"}`}>{tx.readiness}: {percent}%</span></span></summary><div className="border-t p-3"><label className="flex gap-2 text-sm"><input type="checkbox" checked={hasFile} readOnly/> {l==="ru"?"Файл доказательства загружен":l==="uz"?"Dalil fayli yuklangan":"Evidence file uploaded"}</label>{tx.checks.map((text,i)=><label key={text} className="mt-2 flex gap-2 text-sm"><input type="checkbox" checked={checks[i]} onChange={e=>setChecks(v=>v.map((x,n)=>n===i?e.target.checked:x))}/> {text}</label>)}<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder={tx.note} className="mt-3 min-h-20 w-full rounded-lg border p-3 text-sm"/><p className="mt-1 text-xs text-slate-400">{tx.saved}</p></div></details>;
}
