"use client";

import {useEffect,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase/client";
import type {Locale} from "@/lib/accreditation/specialData";

export default function EmployeeEvidenceAssistant({locale:l,indicatorId,hasFile}:{locale:Locale;indicatorId:string;hasFile:boolean}){
 const s=useMemo(()=>createClient(),[]),key=`accreditation-checks-${indicatorId}`,[ready,setReady]=useState(false),[checks,setChecks]=useState([false,false,false]),[response,setResponse]=useState(""),[status,setStatus]=useState("draft"),[editing,setEditing]=useState(true),[saving,setSaving]=useState(false),[msg,setMsg]=useState("");
 const tx={ru:{title:"Подготовка ответа",steps:"Перед отправкой проверьте комплект",checks:["Документ соответствует требованию индикатора","В файле указаны дата, подразделение и ответственный","Файл читается и не содержит лишних персональных данных"],response:"Письменный ответ к загруженным файлам",hint:"Кратко опишите, что подтверждают документы, за какой период они подготовлены и где находится оригинал.",saved:"Письменный ответ сохранён",save:"Сохранить письменный ответ",edit:"Редактировать ответ",locked:"Ответ отправлен на проверку. Редактирование откроется, если администратор вернёт его на доработку.",readiness:"Готовность"},uz:{title:"Javobni tayyorlash",steps:"Yuborishdan oldin to‘plamni tekshiring",checks:["Hujjat indikator talabiga mos","Faylda sana, bo‘linma va mas’ul ko‘rsatilgan","Fayl o‘qiladi va ortiqcha shaxsiy ma’lumot yo‘q"],response:"Yuklangan fayllarga yozma javob",hint:"Hujjatlar nimani tasdiqlashi, qaysi davr uchun tayyorlangani va asl nusxasi qayerdaligini qisqacha yozing.",saved:"Yozma javob saqlandi",save:"Yozma javobni saqlash",edit:"Javobni tahrirlash",locked:"Javob tekshiruvga yuborildi. Administrator qayta ishlashga qaytarsa, tahrirlash ochiladi.",readiness:"Tayyorlik"},en:{title:"Prepare response",steps:"Check the submission before sending",checks:["Document matches the indicator requirement","Date, unit and owner are stated in the file","File is readable and contains no unnecessary personal data"],response:"Written response accompanying the uploaded files",hint:"Briefly explain what the documents prove, their reporting period and where the original is stored.",saved:"Written response saved",save:"Save written response",edit:"Edit response",locked:"The response is under review. Editing will reopen if the administrator returns it for revision.",readiness:"Readiness"}}[l];
 useEffect(()=>{let active=true;try{const v=JSON.parse(localStorage.getItem(key)||"{}");setChecks(Array.isArray(v.checks)?v.checks:[false,false,false])}catch{}void s.from("accreditation_v3_indicators").select("status,response_text").eq("id",indicatorId).maybeSingle().then(({data})=>{if(active&&data){setStatus(data.status);setResponse(data.response_text||"");setEditing(["draft","in_progress"].includes(data.status))}setReady(true)});return()=>{active=false}},[s,key,indicatorId]);
 useEffect(()=>{if(ready)localStorage.setItem(key,JSON.stringify({checks,updatedAt:new Date().toISOString()}))},[ready,key,checks]);
 const complete=checks.filter(Boolean).length+(hasFile?1:0)+(response.trim()?1:0),percent=Math.round(complete/5*100),locked=status==="review"||status==="approved";
 async function save(){if(locked)return;setSaving(true);setMsg("");const values=status==="revision"?{response_text:response.trim(),status:"in_progress",completion_percent:30,submitted_at:null,approved_at:null}:{response_text:response.trim()},{error}=await s.from("accreditation_v3_indicators").update(values).eq("id",indicatorId);setSaving(false);setMsg(error?.message||tx.saved);if(!error){setStatus("in_progress");setEditing(false)}}
 return <section className="mt-4 overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="border-b bg-slate-50 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><h4 className="font-black text-slate-900">{tx.title}</h4><p className="mt-1 text-xs text-slate-500">{tx.steps}</p></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${percent===100?"bg-emerald-100 text-emerald-800":"bg-amber-100 text-amber-900"}`}>{tx.readiness}: {percent}%</span></div></div><div className="grid gap-5 p-4 lg:grid-cols-2"><div><label className="flex gap-2 text-sm"><input type="checkbox" checked={hasFile} readOnly/> {l==="ru"?"Файл-ответ загружен":l==="uz"?"Javob fayli yuklangan":"Response file uploaded"}</label>{tx.checks.map((text,i)=><label key={text} className="mt-3 flex gap-2 text-sm"><input type="checkbox" checked={checks[i]} disabled={locked} onChange={e=>setChecks(v=>v.map((x,n)=>n===i?e.target.checked:x))}/> {text}</label>)}</div><div><label className="text-sm font-bold text-slate-700">{tx.response}</label><textarea value={response} readOnly={locked||!editing} onChange={e=>setResponse(e.target.value)} placeholder={tx.hint} className={`mt-2 min-h-32 w-full rounded-xl border p-3 text-sm ${locked||!editing?"bg-slate-50":"bg-white ring-2 ring-blue-50"}`}/>{locked?<p className="mt-2 text-xs text-amber-700">{tx.locked}</p>:<div className="mt-2 flex flex-wrap gap-2">{!editing&&<button onClick={()=>setEditing(true)} className="rounded-lg bg-blue-50 px-3 py-2 text-sm font-bold text-blue-700">{tx.edit}</button>}{editing&&<button disabled={saving} onClick={()=>void save()} className="rounded-lg bg-blue-700 px-3 py-2 text-sm font-bold text-white disabled:opacity-40">{saving?"…":tx.save}</button>}</div>}{msg&&<p className="mt-2 text-xs font-semibold text-blue-700">{msg}</p>}</div></div></section>;
}
