"use client";
import { useEffect,useMemo,useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { Link } from "@/i18n/routing";
import type { Locale } from "@/lib/accreditation/specialData";
import { accreditationUi } from "@/lib/accreditation/ui";
import NotificationCenter from "./NotificationCenter";
export default function HeadCabinet({locale:l}:{locale:Locale}){const t=accreditationUi[l];const supabase=useMemo(()=>createClient(),[]);const[profile,setProfile]=useState<any>(null);const[loading,setLoading]=useState(true);const[counts,setCounts]=useState({complex:0,special:0});
 useEffect(()=>{let active=true;async function load(){const{data:{user}}=await supabase.auth.getUser();if(!user){location.href=`/${l}/accreditation/login`;return}const{data:p}=await supabase.from('accreditation_v3_profiles').select('*').eq('user_id',user.id).maybeSingle();if(!active)return;setProfile(p);if(p?.approval_status==='approved'){const{data}=await supabase.from('accreditation_v3_indicators').select('project_id,accreditation_v3_projects(code)').eq('responsible_user_id',user.id);const rows=data||[];setCounts({complex:rows.filter((x:any)=>x.accreditation_v3_projects?.code==='complex').length,special:rows.filter((x:any)=>String(x.accreditation_v3_projects?.code||'').startsWith('special-')).length})}setLoading(false)}void load();return()=>{active=false}},[supabase,l]);
 if(loading)return <div className="p-10">...</div>;if(!profile)return <div className="rounded-2xl bg-amber-50 p-6 text-amber-900">{l==='ru'?'Профиль не найден. Зарегистрируйтесь заново.':l==='uz'?'Profil topilmadi. Qayta ro‘yxatdan o‘ting.':'Profile not found. Please register again.'}</div>;
 const pending=profile.approval_status!=='approved'; const tx={ru:{choose:'Выберите вид аккредитации',pending:'Ваш профиль зарегистрирован и ожидает подтверждения администратора. Просматривать индикаторы можно уже сейчас; загрузка материалов станет доступна после подтверждения.',complex:'Комплексная государственная аккредитация',special:'Специальная государственная аккредитация',assigned:'закреплено индикаторов',open:'Открыть индикаторы'},uz:{choose:'Akkreditatsiya turini tanlang',pending:'Profilingiz ro‘yxatdan o‘tdi va administrator tasdig‘ini kutmoqda. Indikatorlarni hozir ko‘rishingiz mumkin; material yuklash tasdiqlangandan so‘ng ochiladi.',complex:'Kompleks davlat akkreditatsiyasi',special:'Maxsus davlat akkreditatsiyasi',assigned:'biriktirilgan indikator',open:'Indikatorlarni ochish'},en:{choose:'Choose accreditation type',pending:'Your profile is registered and awaiting administrator approval. You may view indicators now; material upload becomes available after approval.',complex:'Comprehensive state accreditation',special:'Special state accreditation',assigned:'assigned indicators',open:'Open indicators'}}[l];
 return <div className="space-y-7"><section className="rounded-[28px] bg-gradient-to-r from-blue-700 to-cyan-600 p-8 text-white"><p className="text-sm font-bold uppercase tracking-wider">{profile.job_title||profile.role}</p><h1 className="mt-2 text-3xl font-black">{t.cabinet}</h1><p className="mt-2 text-blue-50">{profile.full_name}</p></section>{pending&&<div className="rounded-2xl border border-amber-200 bg-amber-50 p-5 text-amber-900">{tx.pending}</div>}<NotificationCenter locale={l}/><section><h2 className="text-3xl font-black text-slate-900">{tx.choose}</h2><div className="mt-6 grid gap-6 lg:grid-cols-2"><Link href="/accreditation/complex" className="rounded-[28px] border border-blue-100 bg-white p-8 shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><div className="text-5xl">🏛️</div><h3 className="mt-5 text-2xl font-black text-slate-900">{tx.complex}</h3><p className="mt-3 text-slate-500">{counts.complex} {tx.assigned}</p><div className="mt-6 font-black text-blue-700">{tx.open} →</div></Link><Link href="/accreditation/special" className="rounded-[28px] border border-cyan-100 bg-white p-8 shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><div className="text-5xl">🎓</div><h3 className="mt-5 text-2xl font-black text-slate-900">{tx.special}</h3><p className="mt-3 text-slate-500">{counts.special} {tx.assigned}</p><div className="mt-6 font-black text-cyan-700">{tx.open} →</div></Link></div></section></div>
}
