"use client";
import {useEffect,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase/client";
import {Link} from "@/i18n/routing";
import type {Locale} from "@/lib/accreditation/specialData";
import NotificationCenter from "./NotificationCenter";
import MyPriorityQueue from "./MyPriorityQueue";
type Profile={full_name:string;job_title:string|null;role:string;approval_status:string;is_active:boolean};
type Task={status:string;due_date:string|null;project:{code:string}|null};
export default function HeadCabinet({locale:l}:{locale:Locale}){
 const supabase=useMemo(()=>createClient(),[]),[profile,setProfile]=useState<Profile|null>(null),[tasks,setTasks]=useState<Task[]>([]),[loading,setLoading]=useState(true),[now]=useState(()=>new Date());
 const tx={ru:{title:"Мои индикаторы",pending:"Ваш профиль ожидает подтверждения администратора. Загрузка материалов откроется после подтверждения.",complex:"Комплексная аккредитация",special:"Специальная аккредитация",assigned:"Назначено",revision:"На доработке",review:"На проверке",approved:"Принято",urgent:"Срок до 7 дней",overdue:"Просрочено",open:"Открыть мои индикаторы",all:"Полный перечень",logout:"Выйти",noTasks:"Вам пока не назначены индикаторы. Обратитесь к администратору."},uz:{title:"Mening indikatorlarim",pending:"Profilingiz administrator tasdig‘ini kutmoqda. Material yuklash tasdiqlangandan keyin ochiladi.",complex:"Kompleks akkreditatsiya",special:"Maxsus akkreditatsiya",assigned:"Biriktirilgan",revision:"Qayta ishlashda",review:"Tekshiruvda",approved:"Qabul qilindi",urgent:"7 kungacha",overdue:"Muddati o‘tgan",open:"Mening indikatorlarimni ochish",all:"To‘liq ro‘yxat",logout:"Chiqish",noTasks:"Sizga hali indikatorlar biriktirilmagan. Administratorga murojaat qiling."},en:{title:"My indicators",pending:"Your profile is awaiting administrator approval. Uploads become available after approval.",complex:"Comprehensive accreditation",special:"Special accreditation",assigned:"Assigned",revision:"For revision",review:"Under review",approved:"Approved",urgent:"Due within 7 days",overdue:"Overdue",open:"Open my indicators",all:"Complete list",logout:"Sign out",noTasks:"No indicators have been assigned to you yet. Contact the administrator."}}[l];
 useEffect(()=>{let active=true;(async()=>{const{data:{user}}=await supabase.auth.getUser();if(!user){location.href=`/${l}/accreditation/login`;return}const[{data:p},{data:i}]=await Promise.all([supabase.from("accreditation_v3_profiles").select("full_name,job_title,role,approval_status,is_active").eq("user_id",user.id).maybeSingle(),supabase.from("accreditation_v3_indicators").select("status,due_date,project:accreditation_v3_projects(code)").eq("responsible_user_id",user.id)]);if(active){setProfile(p as Profile|null);setTasks((i||[]) as unknown as Task[]);setLoading(false)}})();return()=>{active=false}},[supabase,l]);
 async function logout(){await supabase.auth.signOut();location.href=`/${l}/accreditation/login`}
 if(loading)return <div className="space-y-4 p-8"><div className="h-32 animate-pulse rounded-3xl bg-slate-200"/><div className="h-56 animate-pulse rounded-3xl bg-slate-100"/></div>;
 if(!profile)return <div className="rounded-2xl bg-amber-50 p-6 text-amber-900">{l==='ru'?'Профиль не найден. Обратитесь к администратору.':l==='uz'?'Profil topilmadi. Administratorga murojaat qiling.':'Profile not found. Contact the administrator.'}</div>;
 const today=now.toISOString().slice(0,10),in7=new Date(now.getTime()+7*86400000).toISOString().slice(0,10),complex=tasks.filter(x=>x.project?.code==='complex').length,special=tasks.length-complex;
 const metrics=[[tx.assigned,tasks.length,"text-blue-800"],[tx.revision,tasks.filter(x=>x.status==='revision').length,"text-red-700"],[tx.review,tasks.filter(x=>x.status==='review').length,"text-amber-700"],[tx.approved,tasks.filter(x=>x.status==='approved').length,"text-emerald-700"],[tx.urgent,tasks.filter(x=>x.status!=='approved'&&x.due_date&&x.due_date>=today&&x.due_date<=in7).length,"text-orange-700"],[tx.overdue,tasks.filter(x=>x.status!=='approved'&&x.due_date&&x.due_date<today).length,"text-red-800"]] as const;
 return <div className="space-y-7"><section className="rounded-[28px] bg-gradient-to-r from-blue-700 to-cyan-600 p-8 text-white"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-wider">{profile.job_title||profile.role}</p><h1 className="mt-2 text-3xl font-black">{tx.title}</h1><p className="mt-2 text-blue-50">{profile.full_name}</p></div><button onClick={()=>void logout()} className="rounded-xl bg-white/15 px-4 py-2 text-sm font-bold ring-1 ring-white/30">{tx.logout}</button></div></section>{profile.approval_status!=='approved'&&<div className="rounded-2xl border border-amber-200 bg-amber-50 p-5 text-amber-900">{tx.pending}</div>}<section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-6">{metrics.map(([label,value,color])=><article key={label} className="rounded-2xl border bg-white p-4 shadow-sm"><b className={`text-3xl ${color}`}>{value}</b><p className="mt-1 text-sm text-slate-500">{label}</p></article>)}</section>{!tasks.length&&<p className="rounded-2xl border border-blue-100 bg-blue-50 p-5 text-blue-900">{tx.noTasks}</p>}<MyPriorityQueue locale={l}/><NotificationCenter locale={l}/><section className="grid gap-6 lg:grid-cols-2">{[[tx.complex,complex,"complex","blue"],[tx.special,special,"special","cyan"]].map(([name,count,path,color])=><article key={String(path)} className="rounded-[28px] border bg-white p-7 shadow-sm"><h2 className="text-2xl font-black text-slate-900">{name}</h2><p className="mt-2 text-slate-500">{count} {tx.assigned.toLowerCase()}</p><div className="mt-5 flex flex-wrap gap-2"><Link href={`/accreditation/${path}?scope=mine`} className={`rounded-xl px-4 py-3 font-bold text-white ${color==='blue'?'bg-blue-700':'bg-cyan-700'}`}>{tx.open} →</Link><Link href={`/accreditation/${path}`} className="rounded-xl bg-slate-100 px-4 py-3 font-bold text-slate-700">{tx.all}</Link></div></article>)}</section></div>
}
