"use client";
import {useCallback,useEffect,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase/client";
import {Link} from "@/i18n/routing";
import type {Locale} from "@/lib/accreditation/specialData";
type N={id:string;kind:string;indicator_id:string|null;title_ru:string;title_uz:string;title_en:string;body_ru:string|null;body_uz:string|null;body_en:string|null;read_at:string|null;created_at:string;indicator:{code:string;project:{code:string}|null}|null};
export default function NotificationCenter({locale:l}:{locale:Locale}){
 const supabase=useMemo(()=>createClient(),[]),[rows,setRows]=useState<N[]>([]),[onlyNew,setOnlyNew]=useState(true);
 const tx={ru:{title:"Уведомления",empty:"Уведомлений нет",read:"Прочитать все",new:"Новые",all:"Все",open:"Открыть индикатор"},uz:{title:"Bildirishnomalar",empty:"Bildirishnomalar yo‘q",read:"Barchasini o‘qish",new:"Yangi",all:"Barchasi",open:"Indikatorni ochish"},en:{title:"Notifications",empty:"No notifications",read:"Mark all read",new:"New",all:"All",open:"Open indicator"}}[l];
 const load=useCallback(async()=>{const{data:{user}}=await supabase.auth.getUser();if(!user)return;const{data}=await supabase.from("accreditation_v6_notifications").select("id,kind,indicator_id,title_ru,title_uz,title_en,body_ru,body_uz,body_en,read_at,created_at,indicator:accreditation_v3_indicators(code,project:accreditation_v3_projects(code))").eq("user_id",user.id).order("created_at",{ascending:false}).limit(50);setRows((data||[]) as unknown as N[])},[supabase]);
 useEffect(()=>{void load();const c=supabase.channel("accreditation-notifications").on("postgres_changes",{event:"INSERT",schema:"public",table:"accreditation_v6_notifications"},()=>void load()).subscribe();return()=>{void supabase.removeChannel(c)}},[supabase,load]);
 async function mark(ids:string[]|null){await supabase.rpc("accreditation_v6_mark_notifications_read",{notification_ids:ids});void load()}
 const value=(n:N,k:"title"|"body")=>n[`${k}_${l}` as keyof N] as string|null,shown=onlyNew?rows.filter(x=>!x.read_at):rows;
 const href=(n:N)=>{const project=n.indicator?.project?.code||"";if(project==='complex')return `/accreditation/complex?scope=mine&q=${encodeURIComponent(n.indicator?.code||'')}`;const slug=project.replace(/^special-/,"");return `/accreditation/special?scope=mine&program=${encodeURIComponent(slug)}&q=${encodeURIComponent(n.indicator?.code||'')}`};
 return <section className="rounded-[26px] border border-slate-200 bg-white p-6 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-2xl font-black text-slate-900">{tx.title}<span className="ml-2 rounded-full bg-red-600 px-2 py-1 text-xs text-white">{rows.filter(x=>!x.read_at).length}</span></h2><div className="flex gap-2"><button onClick={()=>setOnlyNew(true)} className={`rounded-lg px-3 py-2 text-sm font-bold ${onlyNew?'bg-blue-700 text-white':'bg-slate-100'}`}>{tx.new}</button><button onClick={()=>setOnlyNew(false)} className={`rounded-lg px-3 py-2 text-sm font-bold ${!onlyNew?'bg-blue-700 text-white':'bg-slate-100'}`}>{tx.all}</button>{rows.some(x=>!x.read_at)&&<button onClick={()=>void mark(null)} className="rounded-lg bg-blue-50 px-3 py-2 text-sm font-bold text-blue-700">{tx.read}</button>}</div></div><div className="mt-4 max-h-96 space-y-3 overflow-auto">{!shown.length&&<p className="text-slate-500">{tx.empty}</p>}{shown.map(n=><article key={n.id} className={`rounded-xl border p-4 ${n.read_at?'border-slate-100 bg-slate-50':'border-blue-200 bg-blue-50'}`}><div className="flex items-start justify-between gap-4"><div><b className="text-slate-900">{value(n,"title")}</b><p className="mt-1 text-sm text-slate-600">{value(n,"body")}</p>{n.indicator&&<Link href={href(n)} onClick={()=>!n.read_at&&void mark([n.id])} className="mt-2 inline-block text-sm font-bold text-blue-700">{tx.open} →</Link>}</div><time className="shrink-0 text-xs text-slate-400">{new Date(n.created_at).toLocaleString(l)}</time></div></article>)}</div></section>
}
