import { PageHeader } from "@/components/common/PageHeader";
import { Link } from "@/i18n/routing";

const labels = {
  ru: { label:"Самооценка", title:"Внутренняя самооценка института", description:"Системный анализ соответствия образовательной деятельности установленным критериям, выявление сильных сторон и зон развития.", stages:["Планирование и распределение ответственности","Сбор подтверждающих документов","Анализ критериев и индикаторов","Внутренняя проверка доказательств","Формирование отчёта по самооценке","План корректирующих мероприятий"], evidence:"Доказательная база", evidenceText:"В доказательную базу включаются только утверждённые документы, протоколы, отчёты, результаты опросов и проверяемые цифровые данные.", docs:"Перейти к документам" },
  uz: { label:"O‘zini o‘zi baholash", title:"Institutning ichki o‘zini o‘zi baholashi", description:"Ta’lim faoliyatining belgilangan mezonlarga muvofiqligini tizimli tahlil qilish, kuchli tomonlar va rivojlanish yo‘nalishlarini aniqlash.", stages:["Rejalashtirish va mas’uliyatni taqsimlash","Tasdiqlovchi hujjatlarni yig‘ish","Mezon va indikatorlarni tahlil qilish","Dalillarni ichki tekshirish","O‘zini o‘zi baholash hisobotini shakllantirish","Tuzatish choralari rejasini ishlab chiqish"], evidence:"Dalillar bazasi", evidenceText:"Dalillar bazasiga faqat tasdiqlangan hujjatlar, bayonnomalar, hisobotlar, so‘rov natijalari va tekshiriladigan raqamli ma’lumotlar kiritiladi.", docs:"Hujjatlarga o‘tish" },
  en: { label:"Self-assessment", title:"Institutional internal self-assessment", description:"A systematic review of educational activities against established criteria to identify strengths and areas for development.", stages:["Planning and assignment of responsibility","Collection of supporting documents","Review of criteria and indicators","Internal verification of evidence","Preparation of the self-assessment report","Corrective action planning"], evidence:"Evidence base", evidenceText:"The evidence base includes only approved documents, minutes, reports, survey results and verifiable digital data.", docs:"View documents" },
};

export default async function SelfAssessmentPage({params}:{params:Promise<{locale:string}>}) {
  const {locale}=await params; const current=locale==="uz"||locale==="en"?locale:"ru"; const t=labels[current];
  return <main><PageHeader label={t.label} title={t.title} description={t.description}/><section className="container-main py-16 sm:py-20"><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{t.stages.map((stage,index)=><article key={stage} className="rounded-[26px] border border-slate-200 bg-white p-6 shadow-sm"><span className="text-sm font-black text-cyan-700">{String(index+1).padStart(2,"0")}</span><h2 className="mt-4 text-xl font-bold text-slate-950">{stage}</h2></article>)}</div><div className="mt-10 rounded-[30px] bg-gradient-to-r from-[#083b73] to-[#087d83] p-8 text-white sm:p-10"><h2 className="text-3xl font-black">{t.evidence}</h2><p className="mt-4 max-w-4xl leading-8 text-blue-50">{t.evidenceText}</p><Link href="/documents" className="mt-7 inline-flex rounded-xl bg-white px-6 py-3 font-bold text-[#083b73]">{t.docs}</Link></div></section></main>;
}
