"use client";
import { useEffect, useState } from "react";
import { useRouter } from "@/i18n/routing";

type Question = { id:string; question_type:"single"|"multiple"|"scale"|"text"; prompt_ru:string; prompt_uz:string; prompt_en:string; options:Array<{ru:string;uz:string;en:string}>; required:boolean };
type Survey = Record<"title_ru"|"title_uz"|"title_en"|"description_ru"|"description_uz"|"description_en",string>;
const copy={ru:{loading:"Открываем анонимную анкету…",private:"После открытия анкеты связь с вашим профилем заменяется случайным кодом. Ответы не содержат Ф.И.О. или Student ID.",submit:"Отправить анонимно",done:"Спасибо! Опрос пройден анонимно.",back:"Вернуться в кабинет",error:"Не удалось открыть опрос или он уже пройден.",required:"Ответьте на все обязательные вопросы"},uz:{loading:"Anonim so‘rov ochilmoqda…",private:"So‘rov ochilgach, profilingiz bilan bog‘lanish tasodifiy kod bilan almashtiriladi. Javoblarda F.I.Sh. yoki Student ID bo‘lmaydi.",submit:"Anonim yuborish",done:"Rahmat! So‘rov anonim tarzda yakunlandi.",back:"Kabinetga qaytish",error:"So‘rovni ochib bo‘lmadi yoki u avval yakunlangan.",required:"Barcha majburiy savollarga javob bering"},en:{loading:"Opening the anonymous survey…",private:"After opening, the link to your profile is replaced by a random code. Answers contain no name or Student ID.",submit:"Submit anonymously",done:"Thank you! The survey was completed anonymously.",back:"Back to account",error:"The survey could not be opened or is already completed.",required:"Answer all required questions"}} as const;
export default function GenericStudentSurveyForm({locale,id}:{locale:string;id:string}){
 const lang=locale==="uz"||locale==="en"?locale:"ru"; const t=copy[lang]; const router=useRouter();
 const [survey,setSurvey]=useState<Survey|null>(null); const [questions,setQuestions]=useState<Question[]>([]); const [answers,setAnswers]=useState<Record<string,unknown>>({}); const [error,setError]=useState(""); const [done,setDone]=useState(false); const [busy,setBusy]=useState(false);
 useEffect(()=>{void fetch(`/api/student/surveys/${id}/start`,{method:"POST"}).then(async r=>{if(!r.ok){setError(t.error);return;}const d=await r.json();setSurvey(d.survey);setQuestions(d.questions||[]);}).catch(()=>setError(t.error));},[id,t.error]);
 const text=(q:Question)=>q[`prompt_${lang}`]; const optionText=(o:{ru:string;uz:string;en:string})=>o[lang];
 async function submit(){if(questions.some(q=>q.required&&(!(q.id in answers)||answers[q.id]===""||(Array.isArray(answers[q.id])&&!(answers[q.id] as unknown[]).length)))){setError(t.required);return;}setBusy(true);setError("");const r=await fetch(`/api/student/surveys/${id}/submit`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({locale:lang,answers})});setBusy(false);if(r.ok)setDone(true);else setError(t.error);}
 if(done)return <main className="container-main py-16"><div className="mx-auto max-w-2xl rounded-[30px] bg-white p-8 text-center shadow-xl"><div className="text-5xl">✓</div><h1 className="mt-4 text-3xl font-black text-emerald-800">{t.done}</h1><button onClick={()=>router.replace("/student")} className="mt-7 rounded-xl bg-blue-700 px-6 py-3 font-bold text-white">{t.back}</button></div></main>;
 if(error&&!survey)return <main className="container-main py-16 text-center"><p className="font-bold text-red-700">{error}</p><button onClick={()=>router.replace("/student")} className="mt-5 rounded-xl bg-blue-700 px-6 py-3 font-bold text-white">{t.back}</button></main>;
 if(!survey)return <main className="container-main py-16 text-center font-bold text-slate-600">{t.loading}</main>;
 return <main className="container-main py-8 sm:py-12"><div className="mx-auto max-w-3xl"><div className="rounded-[28px] bg-gradient-to-br from-[#083b73] to-[#087d83] p-7 text-white"><h1 className="text-3xl font-black">{survey[`title_${lang}`]}</h1><p className="mt-3 text-blue-50">{survey[`description_${lang}`]}</p></div><p className="mt-5 rounded-2xl border border-cyan-200 bg-cyan-50 p-4 text-sm text-cyan-950">{t.private}</p><div className="mt-6 space-y-5">{questions.map((q,index)=><fieldset key={q.id} className="rounded-3xl border bg-white p-6 shadow-sm"><legend className="px-2 font-black text-slate-900">{index+1}. {text(q)} {q.required&&<span className="text-red-600">*</span>}</legend>{q.question_type==="text"?<textarea maxLength={3000} onChange={e=>setAnswers(a=>({...a,[q.id]:e.target.value}))} className="mt-4 min-h-32 w-full rounded-xl border p-3"/>:q.question_type==="scale"?<div className="mt-4 flex flex-wrap gap-2">{[1,2,3,4,5].map(n=><label key={n} className={`cursor-pointer rounded-xl border px-5 py-3 font-bold ${answers[q.id]===n?"bg-blue-700 text-white":"bg-white"}`}><input className="sr-only" type="radio" name={q.id} onChange={()=>setAnswers(a=>({...a,[q.id]:n}))}/>{n}</label>)}</div>:<div className="mt-4 grid gap-2">{(q.options||[]).map((o,i)=><label key={i} className="flex gap-3 rounded-xl border p-3"><input type={q.question_type==="multiple"?"checkbox":"radio"} name={q.id} onChange={e=>setAnswers(a=>{if(q.question_type!=="multiple")return {...a,[q.id]:i};const old=Array.isArray(a[q.id])?a[q.id] as number[]:[];return {...a,[q.id]:e.target.checked?[...old,i]:old.filter(x=>x!==i)}})}/><span>{optionText(o)}</span></label>)}</div>}</fieldset>)}</div>{error&&<p className="mt-5 rounded-xl bg-red-50 p-4 font-bold text-red-700">{error}</p>}<button disabled={busy} onClick={()=>void submit()} className="mt-7 w-full rounded-2xl bg-emerald-700 px-7 py-4 text-lg font-black text-white disabled:opacity-50">{t.submit}</button></div></main>;
}
