"use client";

import { useEffect, useMemo, useState } from "react";
import Script from "next/script";
import { CheckCircle2, ChevronLeft, ChevronRight, GraduationCap, ShieldCheck } from "lucide-react";
import { doctoralRatingItems, graduateProgrammes, graduateRatingItems, qualitySurveyLabels, type QualitySurveyKind } from "@/data/qualitySurveys";

type State = { profile: Record<string, string>; ratings: number[]; choices: string[]; answers: Record<string, string>; captchaToken: string };
const input = "w-full rounded-2xl border border-slate-300 bg-white px-4 py-3.5 text-slate-900 outline-none focus:border-blue-600 focus:ring-4 focus:ring-blue-100";

declare global { interface Window { onQualitySurveyCaptcha?: (token: string) => void; onQualitySurveyCaptchaExpired?: () => void; turnstile?: { reset: () => void } } }

function RatingGrid({ items, values, onChange }: { items: string[]; values: number[]; onChange: (v: number[]) => void }) {
  return <div className="space-y-4">{items.map((item, index) => <div key={item} className="rounded-2xl border border-slate-200 p-4 sm:p-5"><p className="font-semibold leading-6 text-slate-800">{index + 1}. {item}</p><div className="mt-3 grid grid-cols-5 gap-2">{[1,2,3,4,5].map(value => <button type="button" key={value} aria-label={`${item}: ${value}`} onClick={() => onChange(values.map((old, i) => i === index ? value : old))} className={`min-h-11 rounded-xl border font-black ${values[index] === value ? "border-blue-700 bg-blue-700 text-white" : "border-slate-200 bg-white hover:border-blue-400"}`}>{value}</button>)}</div></div>)}</div>;
}

export default function QualitySurveyForm({ locale, kind }: { locale: string; kind: QualitySurveyKind }) {
  const lang = locale === "uz" || locale === "en" ? locale : "ru";
  const t = qualitySurveyLabels[lang];
  const graduate = kind === "graduates";
  const ratingItems = graduate ? graduateRatingItems : doctoralRatingItems;
  const steps = graduate ? ["Общая информация", "Качество обучения", "Трудоустройство", "Проверка"] : ["Общие сведения", "Обучение и наука", "Предложения", "Проверка"];
  const [step, setStep] = useState(0), [busy, setBusy] = useState(false), [done, setDone] = useState(false), [message, setMessage] = useState("");
  const empty = useMemo<State>(() => ({ profile: {}, ratings: Array(ratingItems.length).fill(0), choices: [], answers: {}, captchaToken: "" }), [ratingItems.length]);
  const [form, setForm] = useState<State>(empty);
  const setProfile = (key: string, value: string) => setForm(s => ({ ...s, profile: { ...s.profile, [key]: value } }));
  const setAnswer = (key: string, value: string) => setForm(s => ({ ...s, answers: { ...s.answers, [key]: value } }));
  const toggle = (value: string) => setForm(s => ({ ...s, choices: s.choices.includes(value) ? s.choices.filter(x => x !== value) : [...s.choices, value] }));
  useEffect(() => { window.onQualitySurveyCaptcha = token => setForm(s => ({...s, captchaToken: token})); window.onQualitySurveyCaptchaExpired = () => setForm(s => ({...s, captchaToken: ""})); return () => { delete window.onQualitySurveyCaptcha; delete window.onQualitySurveyCaptchaExpired; }; }, []);

  function valid() {
    if (step === 0) return graduate ? Boolean(form.profile.graduationYear && form.profile.faculty && form.profile.programme && form.profile.employmentStatus) : Boolean(form.profile.specialty?.trim() && form.profile.course && form.profile.form);
    if (step === 1) return form.ratings.every(v => v >= 1 && v <= 5);
    if (step === 2) return graduate ? Boolean(form.answers.firstJobTiming && form.answers.recommendation) : true;
    return Boolean(form.captchaToken);
  }
  function next() { if (!valid()) return setMessage(t.required); setMessage(""); setStep(v => v + 1); window.scrollTo({top: 0, behavior: "smooth"}); }
  async function submit() {
    if (!valid()) return setMessage(t.required); setBusy(true); setMessage("");
    try { const response = await fetch(`/api/quality-surveys/${kind}/submit`, { method: "POST", headers: {"Content-Type":"application/json"}, body: JSON.stringify({ locale: lang, ...form }) }); if (!response.ok) throw new Error(); setDone(true); }
    catch { setMessage("Не удалось отправить анкету. Попробуйте ещё раз."); window.turnstile?.reset(); setForm(s => ({...s, captchaToken:""})); }
    finally { setBusy(false); }
  }
  if (done) return <main className="container-main py-16"><section className="mx-auto max-w-2xl rounded-[32px] border border-emerald-200 bg-emerald-50 p-10 text-center"><CheckCircle2 className="mx-auto h-16 w-16 text-emerald-700"/><h1 className="mt-5 text-3xl font-black text-emerald-950">{t.success}</h1><p className="mt-3 text-emerald-900">Ответ сохранён анонимно и уже учтён в мониторинге отдела качества.</p></section></main>;

  const title = graduate ? "Опрос выпускников Института" : "Опрос докторантов об условиях обучения и научной деятельности";
  return <main className="container-main py-8 sm:py-12"><header className="rounded-[32px] bg-gradient-to-br from-[#083b73] via-[#0b4f87] to-[#087d83] p-6 text-white shadow-xl sm:p-10"><div className="flex gap-4"><div className="hidden rounded-2xl bg-white/15 p-4 sm:block"><GraduationCap className="h-9 w-9"/></div><div><p className="text-sm font-black uppercase tracking-[.18em] text-cyan-100">Система качества</p><h1 className="mt-3 text-3xl font-black sm:text-5xl">{title}</h1><p className="mt-4 max-w-4xl leading-7 text-blue-50">{graduate ? "Ваши ответы помогут оценить качество образовательных программ, условия обучения и востребованность полученных знаний и навыков на рынке труда." : "Ответы помогут улучшить условия обучения, научно-исследовательской работы и поддержки докторантов Института."}</p><div className="mt-5 flex flex-wrap gap-3 text-sm font-semibold"><span className="rounded-full bg-white/15 px-4 py-2">5–7 минут</span><span className="flex items-center gap-2 rounded-full bg-white/15 px-4 py-2"><ShieldCheck size={17}/>{t.privacy}</span></div></div></div></header>
    <section className="mt-7 rounded-[28px] border bg-white p-5 shadow-sm"><div className="flex justify-between text-sm font-bold text-slate-600"><span>{steps[step]}</span><span>{step+1}/{steps.length}</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full bg-gradient-to-r from-blue-700 to-cyan-600 transition-all" style={{width:`${(step+1)/steps.length*100}%`}}/></div></section>
    <section className="mt-7 rounded-[28px] border bg-white p-5 shadow-sm sm:p-8">
      {step === 0 && (graduate ? <div className="grid gap-6"><Select label="1. Год окончания Института" value={form.profile.graduationYear} onChange={v=>setProfile("graduationYear",v)} options={["2026","2025","2024"]}/><Select label="2. Факультет" value={form.profile.faculty} onChange={v=>setProfile("faculty",v)} options={["Инженерные системы","Прикладные технические квалификации"]}/><Select label="3. Направление подготовки / специальность" value={form.profile.programme} onChange={v=>setProfile("programme",v)} options={graduateProgrammes}/><Select label="4. Ваша текущая занятость" value={form.profile.employmentStatus} onChange={v=>setProfile("employmentStatus",v)} options={["Работаю по полученной специальности","Работаю не по специальности","Продолжаю обучение","Временно не работаю, ищу работу","Временно не работаю и не ищу работу","Нахожусь в декретном отпуске / по уходу за ребёнком","Другое"]}/><label><b className="mb-2 block">5. Если Вы работаете, укажите название организации и должность (необязательно)</b><input className={input} maxLength={500} value={form.profile.organizationPosition||""} onChange={e=>setProfile("organizationPosition",e.target.value)}/></label></div> : <div className="grid gap-6"><label><b className="mb-2 block">1. Направление подготовки (специальность) *</b><input className={input} maxLength={250} value={form.profile.specialty||""} onChange={e=>setProfile("specialty",e.target.value)}/></label><Select label="2. Курс обучения" value={form.profile.course} onChange={v=>setProfile("course",v)} options={["1-й курс","2-й курс","3-й курс"]}/><Select label="3. Форма докторантуры" value={form.profile.form} onChange={v=>setProfile("form",v)} options={["Базовая докторантура (PhD)","Докторантура (DSc)","Самостоятельный соискатель"]}/></div>)}
      {step === 1 && <div><div className="mb-5 rounded-2xl bg-blue-50 p-4 font-semibold text-blue-950">{t.scale}. 3 — затрудняюсь ответить / удовлетворён(а) частично.</div><RatingGrid items={ratingItems} values={form.ratings} onChange={ratings=>setForm(s=>({...s,ratings}))}/></div>}
      {step === 2 && (graduate ? <div className="grid gap-7"><Select label="15. Через какой период после окончания Института Вы нашли первую работу?" value={form.answers.firstJobTiming} onChange={v=>setAnswer("firstJobTiming",v)} options={["До окончания обучения","В течение 3 месяцев","От 3 до 6 месяцев","Более 6 месяцев","Пока не трудоустроился(ась)"]}/><div><b className="mb-3 block">16. Какие компетенции следует усилить? (можно выбрать несколько)</b><div className="grid gap-2 sm:grid-cols-2">{["Практические профессиональные навыки","Работа с современным оборудованием","Цифровые технологии и программное обеспечение","Иностранные языки","Коммуникативные навыки и работа в команде","Предпринимательские навыки","Другое"].map(x=><label key={x} className={`rounded-2xl border p-4 ${form.choices.includes(x)?"border-blue-700 bg-blue-50":"border-slate-200"}`}><input className="mr-3" type="checkbox" checked={form.choices.includes(x)} onChange={()=>toggle(x)}/>{x}</label>)}</div></div><TextArea label="17. Какие дисциплины, темы или практические занятия необходимо добавить или расширить?" value={form.answers.curriculum||""} onChange={v=>setAnswer("curriculum",v)}/><TextArea label="18. Что необходимо улучшить в деятельности Института?" value={form.answers.improvements||""} onChange={v=>setAnswer("improvements",v)}/><Select label="19. Рекомендовали бы Вы обучение в Институте своим знакомым?" value={form.answers.recommendation} onChange={v=>setAnswer("recommendation",v)} options={["Да","Скорее да","Скорее нет","Нет"]}/><TextArea label="20. Дополнительные предложения и пожелания" value={form.answers.suggestions||""} onChange={v=>setAnswer("suggestions",v)}/></div> : <div className="grid gap-6"><TextArea label="23. Какие трудности Вы испытываете в процессе обучения и выполнения диссертационного исследования?" value={form.answers.difficulties||""} onChange={v=>setAnswer("difficulties",v)}/><TextArea label="24. Какие условия или виды поддержки необходимо улучшить в первую очередь?" value={form.answers.support||""} onChange={v=>setAnswer("support",v)}/><TextArea label="25. Ваши предложения по повышению качества подготовки докторантов" value={form.answers.suggestions||""} onChange={v=>setAnswer("suggestions",v)}/></div>)}
      {step === 3 && <div className="grid gap-5"><div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-5 text-emerald-950"><b>Анкета готова к отправке.</b><p className="mt-2 text-sm leading-6">Ответы сохраняются без имени, Student ID, телефона и электронной почты. В админ-панели отображается только обобщённая аналитика и анонимные комментарии.</p></div><div className="rounded-2xl border bg-slate-50 p-4"><Script src="https://challenges.cloudflare.com/turnstile/v0/api.js" strategy="afterInteractive"/><div className="cf-turnstile" data-sitekey={process.env.NEXT_PUBLIC_TURNSTILE_SITE_KEY} data-action={`${kind}_survey`} data-size="flexible" data-callback="onQualitySurveyCaptcha" data-expired-callback="onQualitySurveyCaptchaExpired"/></div></div>}
      {message && <p className="mt-6 rounded-2xl border border-red-200 bg-red-50 p-4 font-semibold text-red-800">{message}</p>}
      <div className="mt-8 flex flex-col-reverse gap-3 border-t pt-6 sm:flex-row sm:justify-between"><button disabled={step===0||busy} onClick={()=>{setMessage("");setStep(v=>v-1)}} className="inline-flex items-center justify-center gap-2 rounded-2xl border px-6 py-3.5 font-black disabled:opacity-40"><ChevronLeft size={19}/>{t.back}</button>{step<3?<button onClick={next} className="inline-flex items-center justify-center gap-2 rounded-2xl bg-blue-700 px-7 py-3.5 font-black text-white">{t.next}<ChevronRight size={19}/></button>:<button disabled={busy} onClick={submit} className="rounded-2xl bg-emerald-700 px-8 py-3.5 font-black text-white disabled:opacity-50">{busy?t.sending:t.submit}</button>}</div>
    </section></main>;
}

function Select({label,value,onChange,options}:{label:string;value?:string;onChange:(v:string)=>void;options:string[]}) { return <label><b className="mb-2 block">{label} *</b><select className={input} value={value||""} onChange={e=>onChange(e.target.value)}><option value="">Выберите вариант</option>{options.map(x=><option key={x}>{x}</option>)}</select></label> }
function TextArea({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}) { return <label><b className="mb-2 block">{label}</b><textarea className={`${input} min-h-32`} maxLength={3000} value={value} onChange={e=>onChange(e.target.value)}/></label> }
