"use client";
import { surveyText, qualityAnswerLabel } from "@/lib/surveyI18n";
import { useCallback, useEffect, useMemo, useState } from "react";
import { doctoralRatingItems, graduateRatingItems, type QualitySurveyKind } from "@/data/qualitySurveys";

type Row={id:string;created_at:string;locale:string;profile:Record<string,string>;ratings:number[];choices:string[];answers:Record<string,string>};
const csv=(v:unknown)=>`"${String(v??"").replaceAll('"','""')}"`;
export default function QualitySurveyAdmin({locale,kind}:{locale:string;kind:QualitySurveyKind}) {
  const tr = (text: string) => surveyText(locale, text);
  const graduate=kind==="graduates", items=graduate?graduateRatingItems:doctoralRatingItems;
  const [rows,setRows]=useState<Row[]>([]),[week,setWeek]=useState(0),[loading,setLoading]=useState(true),[from,setFrom]=useState(""),[to,setTo]=useState(""),[group,setGroup]=useState("");
  const load=useCallback(async()=>{setLoading(true);const q=new URLSearchParams({from,to});const r=await fetch(`/api/admin/quality-surveys/${kind}?${q}`,{cache:"no-store"});if(r.ok){const data=await r.json();setRows(data.rows||[]);setWeek(data.week||0)}setLoading(false)},[kind,from,to]);
  useEffect(()=>{void load()},[load]);
  const groupKey=graduate?"programme":"form";
  const groups=useMemo(()=>Array.from(new Set(rows.map(r=>r.profile[groupKey]).filter(Boolean))).sort(),[rows,groupKey]);
  const filtered=useMemo(()=>group?rows.filter(r=>r.profile[groupKey]===group):rows,[rows,group,groupKey]);
  const averages=items.map((_,i)=>{const v=filtered.map(r=>Number(r.ratings[i])).filter(Number.isFinite);return v.length?Math.round(v.reduce((a,b)=>a+b,0)/v.length*100)/100:0});
  const avgOverall=averages.length?averages[graduate?8:17]:0;
  const positive=graduate?Math.round(filtered.filter(r=>["Да","Скорее да"].includes(r.answers.recommendation)).length/Math.max(1,filtered.length)*100):Math.round(filtered.filter(r=>Number(r.ratings[18])>=4).length/Math.max(1,filtered.length)*100);
  const distribution=groups.map(g=>({g,n:rows.filter(r=>r.profile[groupKey]===g).length})).sort((a,b)=>b.n-a.n);
  function exportCsv(){const profileKeys=Array.from(new Set(filtered.flatMap(r=>Object.keys(r.profile))));const head=["date","locale",...profileKeys,...items.map((_,i)=>`rating_${i+1}`),"choices","answers"];const body=[head.map(csv).join(";"),...filtered.map(r=>[r.created_at,r.locale,...profileKeys.map(key=>r.profile[key]||""),...r.ratings,r.choices.join(", "),Object.entries(r.answers).map(([k,v])=>`${qualityAnswerLabel(locale,k)}: ${k === "firstJobTiming" || k === "recommendation" ? tr(v) : v}`).join(" | ")].map(csv).join(";"))].join("\r\n");const url=URL.createObjectURL(new Blob(["\uFEFF"+body],{type:"text/csv;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download=`${kind}-survey.csv`;a.click();URL.revokeObjectURL(url)}
  return <div className="space-y-6"><header className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-black text-slate-900 sm:text-4xl">{graduate?tr("Опрос выпускников"):tr("Опрос докторантов")}</h1><p className="mt-2 text-slate-500">{tr("Мониторинг обновляется сразу после поступления новой анкеты")}</p></div><button onClick={exportCsv} disabled={!filtered.length} className="rounded-xl bg-emerald-700 px-5 py-3 font-bold text-white disabled:opacity-40">{tr("Экспорт CSV")}</button></header>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Всего анкет",rows.length],["За 7 дней",week],["Средняя общая оценка",`${avgOverall}/5`],[graduate?"Рекомендуют Институт":"Рекомендуют докторантуру",`${positive}%`]].map(([l,v])=><section key={String(l)} className="rounded-2xl bg-white p-5 shadow-sm"><p className="text-sm font-semibold text-slate-500">{tr(String(l))}</p><strong className="mt-2 block text-3xl text-blue-700">{v}</strong></section>)}</div>
    <section className="grid gap-3 rounded-2xl bg-white p-4 shadow-sm md:grid-cols-3"><select value={group} onChange={e=>setGroup(e.target.value)} className="rounded-xl border bg-white p-3"><option value="">{graduate?tr("Все направления"):tr("Все формы докторантуры")}</option>{groups.map(g=><option key={g} value={g}>{tr(g)}</option>)}</select><input type="date" value={from} onChange={e=>setFrom(e.target.value)} className="rounded-xl border p-3" aria-label={tr("Дата от")}/><input type="date" value={to} onChange={e=>setTo(e.target.value)} className="rounded-xl border p-3" aria-label={tr("Дата до")}/></section>
    <div className="grid gap-6 xl:grid-cols-2"><section className="rounded-2xl bg-white p-5 shadow-sm"><h2 className="text-xl font-black">{tr("Средние оценки")}</h2><div className="mt-4 space-y-3">{items.map((x,i)=><div key={x}><div className="flex gap-3 text-sm"><span className="flex-1">{i+1}. {tr(x)}</span><b>{averages[i]}/5</b></div><div className="mt-1 h-2 rounded-full bg-slate-100"><div className="h-full rounded-full bg-blue-600" style={{width:`${averages[i]*20}%`}}/></div></div>)}</div></section><section className="rounded-2xl bg-white p-5 shadow-sm"><h2 className="text-xl font-black">{tr("Количество по категориям")}</h2><div className="mt-4 space-y-3">{distribution.map(x=><div key={x.g} className="flex items-center justify-between gap-4 rounded-xl border p-3"><span className="text-sm">{tr(x.g)}</span><b>{x.n}</b></div>)}{!distribution.length&&<p className="text-slate-500">{tr("Пока нет данных")}</p>}</div></section></div>
    <section><h2 className="mb-4 text-2xl font-black">{tr("Анонимные ответы и комментарии")}</h2>{loading?<p className="rounded-2xl bg-white p-8">{tr("Загрузка…")}</p>:<div className="space-y-3">{filtered.map(r=><details key={r.id} className="rounded-2xl bg-white p-5 shadow-sm"><summary className="cursor-pointer list-none"><div className="flex flex-wrap justify-between gap-3"><div><b>{tr(r.profile[groupKey]||r.profile.specialty||"")}</b><p className="text-sm text-slate-500">{tr((graduate?r.profile.graduationYear:r.profile.course)||"")}</p></div><div className="text-right"><b>{r.ratings[graduate?8:17]}/5</b><p className="text-xs text-slate-500">{new Date(r.created_at).toLocaleString(locale)}</p></div></div></summary><div className="mt-4 grid gap-3 border-t pt-4 text-sm">{Object.entries(r.answers).filter(([,v])=>v).map(([k,v])=><p key={k}><b>{qualityAnswerLabel(locale,k)}:</b> {k === "firstJobTiming" || k === "recommendation" ? tr(v) : v}</p>)}{r.choices.length>0&&<p><b>{tr("Выбранные компетенции:")}</b> {r.choices.map(tr).join(", ")}</p>}</div></details>)}{!filtered.length&&<p className="rounded-2xl bg-white p-8 text-slate-500">{tr("Анкеты пока не поступили")}</p>}</div>}</section>
  </div>;
}
