import { PageHeader } from "@/components/common/PageHeader";
import { Link } from "@/i18n/routing";

const labels={
  ru:{label:"Открытые материалы",title:"Открытость и доказательность",description:"Публичные материалы системы внутреннего обеспечения качества образования.",items:[["Нормативные документы","Утверждённые положения, регламенты и формы","/documents"],["Мониторинг качества","Направления мониторинга и порядок публикации результатов","/monitoring"],["Аналитические материалы","Подход к анализу данных и подготовке рекомендаций","/analytics"],["Новости отдела","Информация о проведённых мероприятиях и изменениях","/news"],["Обращения","Канал обратной связи для участников образовательного процесса","/appeals"]],note:"Числовые показатели публикуются только после документального подтверждения и указания периода обновления."},
  uz:{label:"Ochiq materiallar",title:"Ochiqlik va dalillilik",description:"Ta’lim sifatini ichki ta’minlash tizimining ochiq materiallari.",items:[["Me’yoriy hujjatlar","Tasdiqlangan nizomlar, reglamentlar va shakllar","/documents"],["Sifat monitoringi","Monitoring yo‘nalishlari va natijalarni e’lon qilish tartibi","/monitoring"],["Tahliliy materiallar","Ma’lumotlarni tahlil qilish va tavsiyalar tayyorlash yondashuvi","/analytics"],["Bo‘lim yangiliklari","O‘tkazilgan tadbirlar va o‘zgarishlar haqida ma’lumot","/news"],["Murojaatlar","Ta’lim jarayoni ishtirokchilari uchun qayta aloqa kanali","/appeals"]],note:"Raqamli ko‘rsatkichlar faqat hujjat bilan tasdiqlangandan va yangilanish davri ko‘rsatilgandan keyin e’lon qilinadi."},
  en:{label:"Open resources",title:"Transparency and evidence",description:"Public resources of the internal education quality assurance system.",items:[["Regulatory documents","Approved policies, procedures and templates","/documents"],["Quality monitoring","Monitoring areas and publication approach","/monitoring"],["Analytical resources","Approach to data analysis and recommendations","/analytics"],["Department news","Information on activities and improvements","/news"],["Appeals","Feedback channel for education stakeholders","/appeals"]],note:"Metrics are published only after documentary verification and with a stated update period."}
};
export default async function OpenDataPage({params}:{params:Promise<{locale:string}>}){const{locale}=await params;const current=locale==="uz"||locale==="en"?locale:"ru";const t=labels[current];return <main><PageHeader label={t.label} title={t.title} description={t.description}/><section className="container-main py-16"><div className="grid gap-5 md:grid-cols-2">{t.items.map(([title,text,href])=><Link key={href} href={href} className="rounded-[26px] border border-slate-200 bg-white p-7 shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><h2 className="text-2xl font-black text-slate-950">{title}</h2><p className="mt-3 leading-7 text-slate-600">{text}</p><span className="mt-5 inline-block font-bold text-blue-700">→</span></Link>)}</div><p className="mt-8 rounded-2xl border border-cyan-200 bg-cyan-50 p-6 leading-7 text-cyan-950">{t.note}</p></section></main>}
