import { Link } from "@/i18n/routing";
import { ArrowUpRight, BarChart3, ClipboardCheck, FileText, GraduationCap, MessageSquareText, ShieldCheck } from "lucide-react";
const copy={
 ru:{label:"Выберите действие",title:"Сервисы системы качества",accreditation:"Аккредитация",accreditationText:"Индикаторы, ответственные и материалы. Комплексная и специализированная аккредитация.",complex:"Комплексная",special:"Специализированная",survey:"Опросы",surveyText:"Ваш опыт помогает улучшать образование.",student:"Студентам",employer:"Работодателям",graduate:"Выпускникам",doctoral:"Докторантам",appeal:"Электронные обращения",appealText:"Задайте вопрос или предложите улучшение. Отслеживайте ответ по коду.",send:"Подать обращение",documents:"Документы",documentText:"Положения, регламенты и формы",monitoring:"Мониторинг",monitoringText:"Направления контроля качества",self:"Самооценка",selfText:"Внутренняя оценка и развитие",hemis:"Тест HEMIS",hemisText:"Проверка знаний преподавателей"},
 uz:{label:"Amalni tanlang",title:"Sifat tizimi xizmatlari",accreditation:"Akkreditatsiya",accreditationText:"Indikatorlar, mas’ullar va materiallar. Kompleks va maxsus akkreditatsiya.",complex:"Kompleks",special:"Maxsus",survey:"So‘rovlar",surveyText:"Tajribangiz ta’limni yaxshilashga yordam beradi.",student:"Talabalar uchun",employer:"Ish beruvchilar uchun",graduate:"Bitiruvchilar uchun",doctoral:"Doktorantlar uchun",appeal:"Elektron murojaatlar",appealText:"Savol bering yoki taklif kiriting. Javobni kod orqali kuzating.",send:"Murojaat yuborish",documents:"Hujjatlar",documentText:"Nizomlar, reglamentlar va shakllar",monitoring:"Monitoring",monitoringText:"Ta’lim sifati nazorati yo‘nalishlari",self:"O‘zini o‘zi baholash",selfText:"Ichki baholash va rivojlanish",hemis:"HEMIS testi",hemisText:"O‘qituvchilar bilimini tekshirish"},
 en:{label:"Choose an action",title:"Quality system services",accreditation:"Accreditation",accreditationText:"Indicators, owners and evidence. Institutional and programme accreditation.",complex:"Institutional",special:"Programme",survey:"Surveys",surveyText:"Your experience helps improve education.",student:"Students",employer:"Employers",graduate:"Graduates",doctoral:"Doctoral students",appeal:"Online appeals",appealText:"Ask a question or suggest an improvement. Track the response with your code.",send:"Submit an appeal",documents:"Documents",documentText:"Policies, procedures and templates",monitoring:"Monitoring",monitoringText:"Education quality control areas",self:"Self-assessment",selfText:"Internal review and development",hemis:"HEMIS test",hemisText:"Teacher knowledge assessment"}
};
export function ServiceHub({locale}:{locale:string}){
 const l=locale==='uz'||locale==='en'?locale:'ru',t=copy[l];
 return <section className="container-main py-10" aria-labelledby="service-title"><p className="section-eyebrow">{t.label}</p><h2 id="service-title" className="mt-2 text-3xl font-bold tracking-tight">{t.title}</h2>
 <div className="bento-grid mt-6">
  <article className="bento-card bento-accreditation"><ShieldCheck size={30}/><h3 className="mt-5 text-2xl font-semibold">{t.accreditation}</h3><p className="mt-3 max-w-sm text-sm leading-6 text-blue-100">{t.accreditationText}</p><div className="mt-auto flex flex-wrap gap-2 pt-8"><Link href="/accreditation?type=complex" className="bento-chip">{t.complex}<ArrowUpRight size={16}/></Link><Link href="/accreditation?type=special" className="bento-chip">{t.special}<ArrowUpRight size={16}/></Link></div></article>
  <article className="bento-card bento-surveys"><ClipboardCheck size={26} className="text-blue-700"/><h3 className="mt-4 text-2xl font-semibold">{t.survey}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{t.surveyText}</p><div className="mt-5 grid grid-cols-2 gap-2">{[[t.student,"teacher"],[t.employer,"employers"],[t.graduate,"graduates"],[t.doctoral,"doctoral"]].map(([label,path])=><Link key={path} href={`/surveys/${path}`} className="survey-service-link">{label}<ArrowUpRight size={15}/></Link>)}</div></article>
  <article className="bento-card bento-appeals"><MessageSquareText size={26} className="text-teal-700"/><h3 className="mt-4 text-2xl font-semibold">{t.appeal}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{t.appealText}</p><Link href="/appeals" className="mt-auto inline-flex items-center gap-2 pt-5 text-sm font-bold text-teal-800">{t.send}<ArrowUpRight size={16}/></Link></article>
  {([[t.documents,t.documentText,"/documents",FileText],[t.monitoring,t.monitoringText,"/monitoring",BarChart3],[t.self,t.selfText,"/self-assessment",ClipboardCheck],[t.hemis,t.hemisText,"/teacher/login",GraduationCap]] as const).map(([title,description,href,Icon])=><Link key={String(href)} href={String(href)} className="bento-card bento-small"><Icon size={23} className="text-blue-700"/><h3 className="mt-4 font-semibold">{String(title)}</h3><p className="mt-2 text-sm leading-5 text-slate-500">{String(description)}</p><ArrowUpRight size={16} className="absolute right-5 top-5 text-slate-400"/></Link>)}
 </div></section>;
}
